export type GraceFaq = {id:string;question:string;answer:string;keywords:string[];href?:string;linkLabel?:string};

export const GRACE_FAQS:GraceFaq[] = [
 {id:'about',question:'What is KOC?',answer:'KOC means Kharis On Campus. It is a fellowship community centred on prayer, the Word and sharing the gospel, with friendship and support as we grow in faith. Connect with your KOC team to learn about its fellowship.',keywords:['what is koc','what does koc','about koc','kharis','what is fellowship']},
 {id:'apply',question:'How do I apply to start a KOC?',answer:'Select Apply here and complete the trainee request with a clear photo of your face. No username, password or sign-in is needed. Apply to lead an existing KOC or start a new one. An administrator privately reviews your request and photo. Contact email is optional. Submitting or approving a request does not automatically create an account.',keywords:['start a koc','start koc','start a fellowship','new fellowship','apply','application','sign up','signup','register','join koc','campus access'],href:'/signup',linkLabel:'Apply here'},
 {id:'approval',question:'Who approves my account?',answer:'An administrator reviews account applications and assigns the appropriate access. Campus leads are linked to one KOC; cluster leads are linked to their cluster. A pending account needs approval before it can access campus records.',keywords:['approve','approved','approval','pending','rejected','declined','waiting for access','disapprove'],href:'/login',linkLabel:'Check your account'},
 {id:'login',question:'How do I sign in?',answer:'Use Member login with your username and password, or a verified email attached to your account. If your account is still pending, an administrator needs to approve it before you can access your campus records.',keywords:['log in','login','sign in','signin','member login'],href:'/login',linkLabel:'Member login'},
 {id:'password',question:'I forgot my password. What should I do?',answer:'If a verified email is attached to your account, open the password reset page, enter that email and use the newest reset link. If you have a username-only account without a recovery email, contact an administrator. Open it in the same browser where you requested it. Never share your password with Grace or another person. If no email arrives, ask an administrator to help.',keywords:['password','reset','forgot','recovery','reset link'],href:'/forgot-password',linkLabel:'Reset password'},
 {id:'reports',question:'When is my weekly report due?',answer:'Weekly reports are due every Friday before 10pm UK time. Open Weekly report in your campus workspace and submit the figures for the correct week. Unsubmitted weeks remain missing; they are not treated as zero.',keywords:['weekly report','report due','deadline','when submit','friday','10pm','reporting','submit stats','weekly stats'],href:'/login',linkLabel:'Open your workspace'},
 {id:'late',question:'What happens if my report is late?',answer:'A first submission after Friday’s 10pm UK deadline is labelled late and creates an in-app notification for overall leadership. Submit your report as soon as you can. Editing an existing report does not create another late-submission alert.',keywords:['late','missed deadline','overdue','not submitted','missing report'],href:'/login',linkLabel:'Submit your report'},
 {id:'grades',question:'How do grades work?',answer:'Campus leads submit assessment percentages on the Grades page. A score strictly below 59% alerts overall leadership and the campus’s cluster lead. Notification recipients can mark their alerts as read.',keywords:['grades','grade','assessment','academic','exam','percent','percentage','59','58'],href:'/login',linkLabel:'Open your workspace'},
 {id:'campus',question:'Is my account separate from my KOC?',answer:'Yes. Your account is your personal login; your KOC is a separate campus record with its own statistics. Each KOC can have one active campus lead. An administrator assigns that lead, and the KOC’s statistics remain when its lead changes.',keywords:['one leader','one lead','university stats','own stats','separate','campus lead','change leader','assigned campus','my university','my campus'],href:'/login',linkLabel:'Open your workspace'},
 {id:'materials',question:'Where can I read fellowship materials?',answer:'Sign in and open Materials to read resources shared with your campus. Materials are presented in a protected reader without a download action. Overall leadership uploads the resources. No browser can guarantee prevention of every screenshot or screen recording.',keywords:['materials','material','resources','pdf','download','screenshot','recording','read only','documents'],href:'/login',linkLabel:'Read materials'},
 {id:'meeting',question:'When and where does fellowship meet?',answer:'The fellowship flyer invites students to Tuesday fellowship. The time and venue vary by campus, so confirm both with your campus team or cluster lead. Grace does not have a verified meeting timetable for every KOC.',keywords:['meeting','meet','venue','where','fellowship time','tuesday','location','address'],href:'/signup',linkLabel:'Connect with the KOC team'},
 {id:'people',question:'How do I record fellowship attendees?',answer:'Campus leads can use People in their workspace to keep fellowship and branch attendance contacts. Record information for your own campus, and only add details that you have permission to keep.',keywords:['people','attendees','attendance contacts','phone numbers','contact list','members','record contacts'],href:'/login',linkLabel:'Open your workspace'},
 {id:'grace',question:'What can Grace help with?',answer:'I answer common questions about KOC applications, accounts, reporting, grades and materials using verified KOC information, with AI replies when connected. I cannot view private records, approve accounts, change passwords or submit reports. AI questions and recent conversation are sent through Supabase to Groq when connected. Supabase does not store chat text; the browser conversation clears when you reload. FAQ answers remain available when AI is unavailable. Please do not share private information.',keywords:['grace','chatbot','help','what can you','human','support','privacy']},
];

const normalize=(text:string)=>text.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
export function answerGrace(question:string):{faq:GraceFaq|null;answer:string}{
 const query=normalize(question);
 const ranked=GRACE_FAQS.map(faq=>({faq,score:faq.keywords.reduce((score,keyword)=>{
  const phrase=normalize(keyword);return score+(new RegExp(`(?:^| )${phrase}(?: |$)`).test(query)?phrase.split(' ').length*3:0);
 },0)*(faq.id==='late'?4:1)})).sort((a,b)=>b.score-a.score);
 const faq=ranked[0]?.score>=3?ranked[0].faq:null;
 return {faq,answer:faq?.answer??'I don’t have a verified answer to that in my FAQ bank. Try one of the suggested questions, or speak with your campus or cluster lead for personal help. Please don’t share passwords or private student information here.'};
}
