import {leadApplicationSchema,applicationAnswers,type LeadApplicationAnswers,type LeadApplicationInput} from './schema.ts';
type Dependencies={publishableKey:string;claim:(identity:string)=>Promise<boolean>;completed:(requestId:string,answers:LeadApplicationAnswers)=>Promise<boolean>;create:(input:LeadApplicationInput)=>Promise<string>;persist:(userId:string,answers:LeadApplicationAnswers,requestId:string)=>Promise<{user_id:string}>;remove:(userId:string)=>Promise<void>};
const origins=new Set(['https://kocm.vercel.app','https://koccm.vercel.app','http://localhost:5173','http://127.0.0.1:5173']);
export function createLeadApplicationHandler(deps:Dependencies){return async(request:Request)=>{
 const origin=request.headers.get('origin');const headers={'content-type':'application/json','cache-control':'no-store',vary:'Origin',...(origin&&origins.has(origin)?{'access-control-allow-origin':origin}:{})};const respond=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
 if(origin&&!origins.has(origin))return respond({error:'Origin is not allowed.'},403);
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'apikey, content-type, authorization, x-client-info'}});
 if(request.method!=='POST')return respond({error:'Use POST.'},405);
 if(request.headers.get('apikey')!==deps.publishableKey)return respond({error:'Invalid project key.'},401);
 let body:unknown;try{if(!request.headers.get('content-type')?.startsWith('application/json'))throw new Error();const reader=request.body?.getReader();if(!reader)throw new Error();const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>18000){await reader.cancel();throw new Error();}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}body=JSON.parse(new TextDecoder().decode(bytes));}catch{return respond({error:'Invalid request.'},400);}
 const result=leadApplicationSchema.safeParse(body);if(!result.success)return respond({error:'Check all application fields before submitting.'},400);const input=result.data,answers=applicationAnswers(input);
 try{const ip=(request.headers.get('x-forwarded-for')?.split(',')[0].trim()??'unknown').slice(0,100);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const hash=Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,'0')).join('');if(!await deps.claim(hash))return respond({error:'Too many attempts. Try again later.'},429);if(await deps.completed(input.requestId,answers))return respond({ok:true});}catch{return respond({error:'Unable to confirm this application. Try again later.'},400);}
 let userId:string|undefined;try{userId=await deps.create(input);const saved=await deps.persist(userId,answers,input.requestId);if(saved.user_id!==userId)await deps.remove(userId);return respond({ok:true});}catch{if(userId){try{if(await deps.completed(input.requestId,answers))return respond({ok:true});}catch{return respond({error:'Unable to confirm the application yet. Retry with the same details.'},503);}try{await deps.remove(userId);}catch{/* An unclaimed pending account may require server cleanup; no credentials are exposed. */}}return respond({error:'Unable to submit this application. Check the details or try another username.'},400);}
};}
