// @vitest-environment jsdom
import {createElement} from 'react';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({load:vi.fn(),campuses:vi.fn(),build:vi.fn()}));
vi.mock('../lib/academic-analytics-data',()=>({loadAcademicAnalyticsData:mocks.load}));
vi.mock('../lib/koc',()=>({listCampuses:mocks.campuses,friendly:(error:Error)=>error.message}));
vi.mock('../lib/academic-analytics',()=>({academicMetrics:{attendance:'Attendance',prayerMinutes:'Prayer time',evangelismMinutes:'Evangelism time',outreachOutings:'Outreach outings',firstTimers:'First timers'},buildAcademicAnalytics:mocks.build,compareAcademicAnalytics:(current:{weekly:unknown[]},previous:{weekly:unknown[]})=>({weekly:current.weekly.map((row,index)=>({index,label:'Week '+(index+1),current:row,previous:previous.weekly[index]})),percentageChanges:{attendance:100}})}));
import AdminAcademicOverview from '../app/views/admin-academic-overview';
const season={id:'current',name:'2026–2027',start_date:'2026-09-18',end_date:'2027-05-28',deadline_hour:22,time_zone:'Europe/London'};
const previous={...season,id:'previous',name:'2025–2026',start_date:'2025-09-19',end_date:'2026-05-29'};
const historicalReview={rows:[{campusName:'Historical Test Campus',region:'Test Region',page:5,attendance:{2023:11,2024:22},prayerHours:{2023:1,2024:2},evangelismHours:{2023:null,2024:1}}],overall:[{metric:'Test total',unit:'Example units',2023:'110',2024:'220',page:1}],attendanceTrend:[{week:'Week 0',2023:1,2024:2},{week:'Week 1',2023:2,2024:3}]};
const profile={id:'admin',full_name:'Test Administrator',email:'admin@example.test',role:'admin' as const,status:'active' as const,campus_id:null,created_at:''};
function model(selected=season,period='full',noData=false){const totals={attendance:noData?null:20,prayerMinutes:noData?null:120,evangelismMinutes:noData?null:60,outreachOutings:noData?null:2,firstTimers:null};const summary={totals,averages:{...totals,attendance:noData?null:10},observedWeeks:{attendance:noData?0:2},submittedWeeks:noData?0:1,expectedWeeks:2,coverage:noData?0:.5,missingWeeks:1};return{season:selected,period,startDate:selected.start_date,endDate:selected.end_date,elapsedEndDate:'2026-09-25',weeks:[],overall:summary,campuses:[{...summary,campusId:'campus',campusName:'Test Campus',region:'North',clusterId:null}],regions:[{...summary,region:'North'}],weekly:[{academicWeek:1,date:'2026-09-18',label:'18 Sep',totals,submittedWeeks:noData?0:1,expectedWeeks:1}],monthly:[]};}
beforeEach(()=>{vi.clearAllMocks();mocks.load.mockResolvedValue({seasons:[season,previous],reports:[],feedback:[],historicalReview});mocks.campuses.mockResolvedValue([{id:'campus',name:'Test Campus',region:'North'}]);mocks.build.mockImplementation(({season:selected,period})=>model(selected,period));});afterEach(cleanup);
it('loads actual academic years and recomputes mid-year and comparison selections',async()=>{render(createElement(AdminAcademicOverview,{season,profile,jump:vi.fn()}));await screen.findByRole('heading',{name:'Academic-year overview'});fireEvent.click(screen.getByRole('button',{name:'Mid-year · 31 Jan'}));await waitFor(()=>expect(mocks.build).toHaveBeenCalledWith(expect.objectContaining({period:'midyear'})));fireEvent.change(screen.getByLabelText('Compare academic year'),{target:{value:'previous'}});expect(mocks.build).toHaveBeenCalledWith(expect.objectContaining({season:previous}));expect(screen.getByRole('img',{name:/Academic-week trend/})).toBeTruthy();});
it('keeps unreported activity and uncollected feedback unknown and links missing campuses to reports',async()=>{mocks.build.mockImplementation(()=>model(season,'full',true));const jump=vi.fn();render(createElement(AdminAcademicOverview,{season,profile,jump}));await screen.findByRole('heading',{name:'Academic-year overview'});const totals=within(screen.getByRole('region',{name:'Academic-year activity totals'}));expect(totals.getAllByText('—')).toHaveLength(4);expect(screen.getByText('No submitted activity for this period.')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Review missing reports for Test Campus'}));expect(jump).toHaveBeenCalledWith('campus',{campusId:'campus'});});
it('switches totals to weekly averages and regional groups without changing campus permissions',async()=>{render(createElement(AdminAcademicOverview,{season,profile,jump:vi.fn()}));await screen.findByLabelText('Table metric');fireEvent.change(screen.getByLabelText('Table metric'),{target:{value:'attendance'}});fireEvent.click(screen.getByRole('button',{name:'Weekly averages'}));expect(screen.getByText('Average per submitted campus-week')).toBeTruthy();fireEvent.change(screen.getByLabelText('Group table by'),{target:{value:'region'}});expect(within(screen.getByRole('region',{name:'Campus and cluster activity'})).getByText('North')).toBeTruthy();});
it('shows load errors without rendering stale statistics',async()=>{mocks.load.mockRejectedValue(new Error('Administrator access required.'));render(createElement(AdminAcademicOverview,{season,profile,jump:vi.fn()}));expect((await screen.findByRole('alert')).textContent).toBe('Administrator access required.');expect(screen.queryByRole('region',{name:'Academic-year activity totals'})).toBeNull();});

it('loads historical reference values only from the authorised data response',async()=>{render(createElement(AdminAcademicOverview,{season,profile,jump:vi.fn()}));await screen.findByText('Historical Test Campus');expect(screen.getByRole('img',{name:'Historical attendance comparison for 2023 and 2024'})).toBeTruthy();});
it('does not invent historical values when the private reference is unavailable',async()=>{mocks.load.mockResolvedValue({seasons:[season],reports:[],feedback:[],historicalReview:null});render(createElement(AdminAcademicOverview,{season,profile,jump:vi.fn()}));await screen.findByText('No historical review data is available for this account.');expect(screen.queryByRole('img',{name:'Historical attendance comparison for 2023 and 2024'})).toBeNull();});
