// @vitest-environment jsdom
import {createElement} from 'react';
import {it,expect,vi,afterEach} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import CampusWeeklyForm from '../app/views/campus-weekly-form';
import {campusWeeklySections} from '../lib/campus-weekly-form';
import {buildWeeks} from '../lib/reporting';
import {submitCampusWeeklyFeedback,type CampusFeedbackRecord} from '../lib/campus-weekly';
vi.mock('../lib/campus-weekly',()=>({submitCampusWeeklyFeedback:vi.fn()}));
afterEach(cleanup);
const props={season:{id:'test',name:'Test',start_date:'2026-09-18',end_date:'2027-05-28',deadline_hour:22,time_zone:'Europe/London'},profile:{id:'lead',full_name:'Campus Lead',email:'lead@example.org',role:'campus' as const,status:'active' as const,campus_id:'campus',created_at:''},campuses:[{id:'campus',name:'Test University',region:'London',is_active:true}],initialWeek:'2026-09-18'};
it('defaults an empty dashboard week to the latest open reporting week',()=>{render(createElement(CampusWeeklyForm,{...props,initialWeek:''}));expect((screen.getByLabelText('Week ending') as unknown as HTMLSelectElement).value).toBe(buildWeeks(props.season,[]).filter(w=>w.status!=='upcoming').at(-1)?.weekEnding);});
function fill(){for(const section of campusWeeklySections){for(const [key,label,type] of section.fields){if(key==='tonguesRecipients'||key==='evangelismZeroReason')continue;const value=type==='number'?'1':type==='yesno'?'no':type==='date'?'2026-09-18':type==='time'?'18:00':key==='lesson'?'Week 1: Prayer':'Test note';fireEvent.change(screen.getByLabelText(label),{target:{value}});}}fireEvent.change(screen.getByLabelText(/Reason for late submission/),{target:{value:'Reported later'}});}
it('derives identity and requires answers before review',()=>{render(createElement(CampusWeeklyForm,props));expect((screen.getByLabelText('Full name') as HTMLInputElement).readOnly).toBe(true);expect((screen.getByLabelText('University / campus') as HTMLInputElement).value).toBe('Test University');fireEvent.click(screen.getByText('Review feedback'));expect(screen.queryByText('Submit feedback')).toBeNull();expect(screen.getAllByRole('alert').length).toBeGreaterThan(0);});
it('shows review and reports success only after confirmed save',async()=>{let complete!:(value:CampusFeedbackRecord)=>void;vi.mocked(submitCampusWeeklyFeedback).mockReturnValue(new Promise(resolve=>{complete=resolve;}));render(createElement(CampusWeeklyForm,props));fill();fireEvent.click(screen.getByText('Review feedback'));fireEvent.click(screen.getByText('Submit feedback'));expect((screen.getByText('Submitting…') as HTMLButtonElement).disabled).toBe(true);expect(screen.queryByText(/submitted successfully/)).toBeNull();complete({id:'saved'} as CampusFeedbackRecord);await waitFor(()=>expect(screen.getByRole('status').textContent).toContain('submitted successfully'));});
it('keeps review answers and retries with the same id after a failed response',async()=>{vi.mocked(submitCampusWeeklyFeedback).mockRejectedValue(new Error('Network unavailable'));render(createElement(CampusWeeklyForm,props));fill();fireEvent.click(screen.getByText('Review feedback'));fireEvent.click(screen.getByText('Submit feedback'));await screen.findByText('Network unavailable');const first=vi.mocked(submitCampusWeeklyFeedback).mock.calls.at(-1)!;expect(screen.getByText('Week 1: Prayer')).toBeTruthy();fireEvent.click(screen.getByText('Submit feedback'));await waitFor(()=>expect(vi.mocked(submitCampusWeeklyFeedback).mock.calls.at(-1)?.[2]).toBe(first[2]));});
