// @vitest-environment jsdom
import {createElement} from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({list:vi.fn(),submit:vi.fn(),photo:vi.fn()}));
vi.mock('../lib/application-photo',()=>({normalizeApplicationPhoto:mocks.photo}));
vi.mock('../lib/lead-applications',()=>({listApplicationCampuses:mocks.list,submitLeadApplication:mocks.submit}));
vi.mock('../app/theme',()=>({ThemeToggle:()=>null}));
import LeadApplicationForm from '../app/views/lead-application-form';
afterEach(cleanup);beforeEach(()=>{vi.clearAllMocks();mocks.list.mockResolvedValue([{id:'22222222-2222-4222-8222-222222222222',name:'Test Campus',lifecycle_status:'inactive'}]);mocks.submit.mockResolvedValue('request-reference');mocks.photo.mockResolvedValue({blob:new Blob(['png'],{type:'image/png'}),hash:'photo-hash'});URL.createObjectURL=vi.fn(()=> 'blob:photo');URL.revokeObjectURL=vi.fn();});
async function addPhoto(){fireEvent.change(screen.getByLabelText('Clear face photo'),{target:{files:[new File(['png'],'face.png',{type:'image/png'})]}});await screen.findByAltText('Your application face photo');}
async function fill(){await addPhoto();await screen.findByText('Test Campus · Inactive');for(const [label,value] of [['Full name','Campus Applicant'],['Course','History'],['Why would you like to lead a KOC?','I want to support our campus community.'],['Your leadership or fellowship experience','I have helped organise campus prayer meetings.'],['Your availability','Tuesday afternoons'],['Your plan for the campus','I will meet students and organise weekly fellowship.']] as const)fireEvent.change(screen.getByLabelText(new RegExp('^'+label.replace('?','\\?'))),{target:{value}});fireEvent.change(screen.getByLabelText('University'),{target:{value:'22222222-2222-4222-8222-222222222222'}});fireEvent.change(screen.getByLabelText('Year of study'),{target:{value:'2'}});}
it('reviews an application before sending and never displays its password',async()=>{render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review request'));await screen.findByRole('heading',{name:'Review your request'});expect(mocks.submit).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('long-password-123');fireEvent.click(screen.getByText('Submit request'));await screen.findByRole('heading',{name:'Request received'});expect(mocks.submit).toHaveBeenCalledTimes(1);expect(mocks.submit.mock.calls[0][0]).not.toHaveProperty('password');expect(mocks.submit.mock.calls[0][1]).toBeInstanceOf(Blob);});
it('retains review and a stable request ID after a failed submission',async()=>{mocks.submit.mockRejectedValue(new Error('Your application could not be submitted.'));render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review request'));await screen.findByText('Submit request');fireEvent.click(screen.getByText('Submit request'));await screen.findByRole('alert');fireEvent.click(screen.getByText('Submit request'));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledTimes(2));expect(mocks.submit.mock.calls[0][0].requestId).toBe(mocks.submit.mock.calls[1][0].requestId);expect(screen.queryByText('Request received')).toBeNull();});
it('reveals university name and city when starting a new KOC',async()=>{render(createElement(LeadApplicationForm));await screen.findByText('Test Campus · Inactive');fireEvent.click(screen.getByLabelText('Start a KOC at a new university'));expect(screen.getByLabelText('University name')).toBeTruthy();expect(screen.getByLabelText('University city')).toBeTruthy();expect(screen.queryByLabelText('University')).toBeNull();});

it('reviews and submits a new university without selecting an existing campus',async()=>{
 render(createElement(LeadApplicationForm));await addPhoto();await screen.findByText('Test Campus · Inactive');fireEvent.click(screen.getByLabelText('Start a KOC at a new university'));
 for(const [label,value] of [['Full name','Campus Applicant'],['Course','History'],['University name','New Test University'],['University city','Test City'],['Why would you like to lead a KOC?','I want to support our campus community.'],['Your leadership or fellowship experience','I have helped organise campus prayer meetings.'],['Your availability','Tuesday afternoons'],['Your plan for the campus','I will meet students and organise weekly fellowship.']] as const)fireEvent.change(screen.getByLabelText(new RegExp('^'+label.replace('?','\\?'))),{target:{value}});
 fireEvent.click(screen.getByText('Review request'));await screen.findByRole('heading',{name:'Review your request'});expect(screen.getByText('New Test University, Test City')).toBeTruthy();fireEvent.click(screen.getByText('Submit request'));await screen.findByRole('heading',{name:'Request received'});expect(mocks.submit.mock.calls[0][0]).toEqual(expect.objectContaining({kind:'new',campusId:null,newUniversityName:'New Test University',newUniversityCity:'Test City'}));
});

it('preserves answers when editing and replaces the request ID for a changed application',async()=>{
 mocks.submit.mockRejectedValue(new Error('Your application could not be submitted.'));render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review request'));await screen.findByText('Submit request');fireEvent.click(screen.getByText('Submit request'));await screen.findByRole('alert');const first=mocks.submit.mock.calls[0][0].requestId;
 fireEvent.click(screen.getByText('Edit application'));expect((screen.getByLabelText('Full name') as HTMLInputElement).value).toBe('Campus Applicant');fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'Updated Applicant'}});fireEvent.click(screen.getByText('Review request'));await screen.findByText('Updated Applicant');fireEvent.click(screen.getByText('Submit request'));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledTimes(2));expect(mocks.submit.mock.calls[1][0].requestId).not.toBe(first);
});

it("requires a face photo without requiring account credentials",async()=>{render(createElement(LeadApplicationForm));await fill();fireEvent.change(screen.getByLabelText("Clear face photo"),{target:{files:[]}});fireEvent.click(screen.getByText("Review request"));await screen.findByText("Add a clear photo of your face before reviewing your request.");expect(screen.queryByLabelText(/Username|Password/)).toBeNull();expect(mocks.submit).not.toHaveBeenCalled();});
it('changes the request ID when the face photo changes and releases preview URLs',async()=>{mocks.submit.mockRejectedValue(new Error('Retry'));const view=render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review request'));await screen.findByText('Submit request');fireEvent.click(screen.getByText('Submit request'));await screen.findByRole('alert');const first=mocks.submit.mock.calls[0][0].requestId;fireEvent.click(screen.getByText('Edit application'));mocks.photo.mockResolvedValue({blob:new Blob(['new-png'],{type:'image/png'}),hash:'new-photo-hash'});await addPhoto();fireEvent.click(screen.getByText('Review request'));await screen.findByText('Submit request');fireEvent.click(screen.getByText('Submit request'));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledTimes(2));expect(mocks.submit.mock.calls[1][0].requestId).not.toBe(first);view.unmount();expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:photo');});
