import {it,expect,vi} from 'vitest';
import {createLeadApplicationHandler} from '../supabase/functions/lead-application/handler';
const input={username:'New_Lead',fullName:'New Lead',password:'long-test-password',kind:'new',newUniversityName:'Test University',newUniversityCity:'London',course:'Physics',studyYear:2,motivation:'I want to support students through fellowship.',experience:'I have served on a fellowship prayer team.',availability:'Tuesday evenings',plan:'Start with prayer and invite students to meet.',phone:'',requestId:'11111111-1111-4111-8111-111111111111'};
const req=(body:unknown=input)=>new Request('https://test',{method:'POST',headers:{origin:'https://kocm.vercel.app',apikey:'public','content-type':'application/json'},body:JSON.stringify(body)});
function setup(){const claim=vi.fn(async()=>true),completed=vi.fn(async()=>false),create=vi.fn(async()=> 'new-user'),persist=vi.fn<(id:string,answers:unknown,requestId:string)=>Promise<{user_id:string}>>(async()=>({user_id:'new-user'})),remove=vi.fn(async()=>{});return {claim,completed,create,persist,remove,handler:createLeadApplicationHandler({publishableKey:'public',claim,completed,create,persist,remove})};}
it('validates before creating and excludes password from stored answers',async()=>{const s=setup();expect((await s.handler(req({...input,password:'short'}))).status).toBe(400);expect(s.create).not.toHaveBeenCalled();expect(await(await s.handler(req())).json()).toEqual({ok:true});expect(s.persist.mock.calls[0]?.[1]).not.toHaveProperty('password');});
it('handles completed request retries without additional users',async()=>{const s=setup();s.completed.mockResolvedValue(true);expect((await s.handler(req())).status).toBe(200);expect(s.create).not.toHaveBeenCalled();});
it('cleans up new auth user when persistence fails or concurrent retry already won',async()=>{const s=setup();s.persist.mockRejectedValueOnce(new Error('secret'));expect((await s.handler(req())).status).toBe(400);expect(s.remove).toHaveBeenCalledWith('new-user');s.remove.mockClear();s.persist.mockResolvedValue({user_id:'winner'});expect((await s.handler(req())).status).toBe(200);expect(s.remove).toHaveBeenCalledWith('new-user');});
it('enforces quota and browser origin without exposing backend errors',async()=>{const s=setup();s.claim.mockResolvedValue(false);expect((await s.handler(req())).status).toBe(429);expect(s.create).not.toHaveBeenCalled();const bad=req();bad.headers.set('origin','https://evil.test');expect((await s.handler(bad)).status).toBe(403);});

it('allows SDK preflight headers and preserves accepted or uncertain applications after response loss',async()=>{const s=setup();const preflight=await s.handler(new Request('https://test',{method:'OPTIONS',headers:{origin:'https://kocm.vercel.app'}}));expect(preflight.headers.get('access-control-allow-headers')).toContain('authorization');s.persist.mockRejectedValue(new Error('timeout'));s.completed.mockResolvedValueOnce(false).mockResolvedValueOnce(true);expect((await s.handler(req())).status).toBe(200);expect(s.remove).not.toHaveBeenCalled();s.completed.mockResolvedValueOnce(false).mockRejectedValueOnce(new Error('unknown'));expect((await s.handler(req())).status).toBe(503);expect(s.remove).not.toHaveBeenCalled();});
