import {it,expect,vi} from 'vitest';
import {PNG} from 'pngjs';
import {createLeadApplicationHandler,canonicalApplicationPhoto} from '../supabase/functions/lead-application/handler';
const input={fullName:'New Lead',kind:'new',newUniversityName:'Test University',newUniversityCity:'London',course:'Physics',studyYear:2,motivation:'I want to support students through fellowship.',experience:'I have served on a fellowship prayer team.',availability:'Tuesday evenings',plan:'Start with prayer and invite students to meet.',phone:'',requestId:'11111111-1111-4111-8111-111111111111'};
const png=PNG.sync.write(new PNG({width:2,height:2}));
const req=(body:unknown=input,photo:Uint8Array|null=png)=>{const data=new FormData();data.set('application',JSON.stringify(body));if(photo)data.set('photo',new Blob([Uint8Array.from(photo).buffer],{type:'image/png'}),'photo.png');return new Request('https://test',{method:'POST',headers:{origin:'https://kocm.vercel.app',apikey:'public'},body:data});};
function setup(){const claim=vi.fn(async()=>true),completed=vi.fn<(id:string,answers:unknown,hash:string)=>Promise<string|null>>(async()=>null),upload=vi.fn(async()=>{}),persist=vi.fn<(answers:unknown,id:string,path:string,hash:string)=>Promise<string>>(async()=> '22222222-2222-4222-8222-222222222222');return {claim,completed,upload,persist,handler:createLeadApplicationHandler({publishableKey:'public',claim,completed,upload,persist})};}
it('persists a public application and private sanitized photo without credentials or Auth side effects',async()=>{const s=setup();const result=await s.handler(req());expect(await result.json()).toEqual({ok:true,reference:'22222222-2222-4222-8222-222222222222'});expect(s.upload).toHaveBeenCalledTimes(1);expect(s.persist.mock.calls[0]).not.toContain('password');});
it('rejects credential payload, missing photos and spoofed PNGs',async()=>{for(const r of [req({...input,username:'lead',password:'password'}),req(input,null),req(input,new TextEncoder().encode('not a png'))]){const s=setup();expect((await s.handler(r)).status).toBe(400);expect(s.upload).not.toHaveBeenCalled();expect(s.persist).not.toHaveBeenCalled();}});
it('limits request size and claims quota before expensive photo work',async()=>{const s=setup();s.claim.mockResolvedValue(false);expect((await s.handler(req())).status).toBe(429);expect(s.upload).not.toHaveBeenCalled();const big=setup();expect((await big.handler(req(input,new Uint8Array(2300000)))).status).toBe(413);expect(big.upload).not.toHaveBeenCalled();});
it('deduplicates retries by canonical photo hash and answers',async()=>{const s=setup();s.completed.mockResolvedValue('22222222-2222-4222-8222-222222222222');expect((await s.handler(req())).status).toBe(200);expect(s.upload).not.toHaveBeenCalled();expect(s.persist).not.toHaveBeenCalled();expect(s.completed.mock.calls[0]?.[2]).toMatch(/^[a-f0-9]{64}$/);});
it('returns only confirmed success after response loss and never deletes uploaded photos',async()=>{const s=setup();s.persist.mockRejectedValue(new Error('provider secret'));s.completed.mockResolvedValueOnce(null).mockResolvedValueOnce('22222222-2222-4222-8222-222222222222');expect((await s.handler(req())).status).toBe(200);s.completed.mockResolvedValueOnce(null).mockRejectedValueOnce(new Error('unknown'));const response=await s.handler(req());expect(response.status).toBe(503);expect(await response.text()).not.toContain('secret');});
it('strips metadata by decoding and re-encoding a bounded PNG',()=>{expect(PNG.sync.read(Buffer.from(canonicalApplicationPhoto(png))).width).toBe(2);const large=PNG.sync.write(new PNG({width:1025,height:1}));expect(()=>canonicalApplicationPhoto(large)).toThrow();});
it('rejects malformed headers, forbidden origins, old JSON payloads and duplicate fields',async()=>{const s=setup();const json=new Request('https://test',{method:'POST',headers:{apikey:'public','content-type':'application/json'},body:JSON.stringify({...input,username:'obsolete'})});expect((await s.handler(json)).status).toBe(400);const bad=req();bad.headers.set('origin','https://evil.test');expect((await s.handler(bad)).status).toBe(403);const key=req();key.headers.set('apikey','bad');expect((await s.handler(key)).status).toBe(401);const data=new FormData();data.append('application',JSON.stringify(input));data.append('application',JSON.stringify(input));data.append('photo',new Blob([Uint8Array.from(png).buffer],{type:'image/png'}));expect((await s.handler(new Request('https://test',{method:'POST',headers:{apikey:'public'},body:data}))).status).toBe(400);expect(s.upload).not.toHaveBeenCalled();});
it('re-encoded photos contain only image chunks, never source metadata',()=>{const clean=Buffer.from(canonicalApplicationPhoto(png));let offset=8;const chunks:string[]=[];while(offset<clean.length){const length=clean.readUInt32BE(offset);chunks.push(clean.toString('ascii',offset+4,offset+8));offset+=length+12;}expect(chunks.every(chunk=>['IHDR','IDAT','IEND'].includes(chunk))).toBe(true);});
it('rejects corrupt PNG CRC and unsupported interlacing before private upload',async()=>{const corrupt=Uint8Array.from(png);corrupt[corrupt.length-1]^=1;const interlaced=Uint8Array.from(png);interlaced[28]=1;for(const bytes of [corrupt,interlaced]){const s=setup();expect((await s.handler(req(input,bytes))).status).toBe(400);expect(s.upload).not.toHaveBeenCalled();}});
it('strips source gamma metadata from a decoded photo',()=>{const image=new PNG({width:2,height:2});image.gamma=0.45;const source=PNG.sync.write(image);expect(source.toString('latin1')).toContain('gAMA');const cleaned=Buffer.from(canonicalApplicationPhoto(source));expect(cleaned.toString('latin1')).not.toContain('gAMA');});
