import {beforeEach,afterEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({rpc:vi.fn(),from:vi.fn(),fetch:vi.fn()}));
vi.mock('../lib/supabase',()=>({SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-key',supabase:()=>({rpc:mocks.rpc,from:mocks.from})}));
import {submitLeadApplication,listApplicationCampuses} from '../lib/lead-applications';
const application={requestId:'11111111-1111-4111-8111-111111111111',fullName:'Campus Lead',kind:'existing',campusId:'22222222-2222-4222-8222-222222222222',course:'History',studyYear:2,motivation:'I want to support campus fellowship.',experience:'I have helped organise prayer meetings.',availability:'Tuesday afternoons',plan:'I will meet students and organise fellowship.'};
beforeEach(()=>{vi.clearAllMocks();vi.stubGlobal('fetch',mocks.fetch);});afterEach(()=>vi.unstubAllGlobals());
it('loads public campus options',async()=>{mocks.rpc.mockResolvedValue({data:[],error:null});expect(await listApplicationCampuses()).toEqual([]);});
it('sends multipart request and photo without session credentials',async()=>{mocks.fetch.mockResolvedValue({ok:true,json:async()=>({ok:true,reference:application.requestId})});expect(await submitLeadApplication(application,new Blob(['png'],{type:'image/png'}))).toBe(application.requestId);const options=mocks.fetch.mock.calls[0][1];expect(options.credentials).toBe('omit');expect(options.headers).toEqual({apikey:'public-key'});expect(JSON.parse(options.body.get('application'))).not.toHaveProperty('password');expect(options.body.get('photo')).toBeTruthy();});
it('rejects unconfirmed responses and reuses the same retry payload',async()=>{mocks.fetch.mockResolvedValue({ok:false,json:async()=>({})});const photo=new Blob(['png']);await expect(submitLeadApplication(application,photo)).rejects.toThrow(/Retry/);await expect(submitLeadApplication(application,photo)).rejects.toThrow();expect(mocks.fetch.mock.calls[0][1].body.get('application')).toBe(mocks.fetch.mock.calls[1][1].body.get('application'));});
