// @vitest-environment jsdom
import {createElement} from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({list:vi.fn(),submit:vi.fn()}));
vi.mock('../lib/lead-applications',()=>({listApplicationCampuses:mocks.list,submitLeadApplication:mocks.submit}));
vi.mock('../app/theme',()=>({ThemeToggle:()=>null}));
import LeadApplicationForm from '../app/views/lead-application-form';
afterEach(cleanup);beforeEach(()=>{vi.clearAllMocks();mocks.list.mockResolvedValue([{id:'22222222-2222-4222-8222-222222222222',name:'Test Campus',lifecycle_status:'inactive'}]);mocks.submit.mockResolvedValue(undefined);});
async function fill(){await screen.findByText('Test Campus · Inactive');for(const [label,value] of [['Full name','Campus Applicant'],['Username','campus_applicant'],['Password','long-password-123'],['Course','History'],['Why would you like to lead a KOC?','I want to support our campus community.'],['Your leadership or fellowship experience','I have helped organise campus prayer meetings.'],['Your availability','Tuesday afternoons'],['Your plan for the campus','I will meet students and organise weekly fellowship.']] as const)fireEvent.change(screen.getByLabelText(new RegExp('^'+label.replace('?','\\?'))),{target:{value}});fireEvent.change(screen.getByLabelText('University'),{target:{value:'22222222-2222-4222-8222-222222222222'}});fireEvent.change(screen.getByLabelText('Year of study'),{target:{value:'2'}});}
it('reviews an application before sending and never displays its password',async()=>{render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review application'));await screen.findByRole('heading',{name:'Review your application'});expect(mocks.submit).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('long-password-123');fireEvent.click(screen.getByText('Submit application'));await screen.findByRole('heading',{name:'Application received'});expect(mocks.submit).toHaveBeenCalledTimes(1);expect(mocks.submit.mock.calls[0][0]).not.toHaveProperty('email');});
it('retains review and a stable request ID after a failed submission',async()=>{mocks.submit.mockRejectedValue(new Error('Your application could not be submitted.'));render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review application'));await screen.findByText('Submit application');fireEvent.click(screen.getByText('Submit application'));await screen.findByRole('alert');fireEvent.click(screen.getByText('Submit application'));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledTimes(2));expect(mocks.submit.mock.calls[0][0].requestId).toBe(mocks.submit.mock.calls[1][0].requestId);expect(screen.queryByText('Application received')).toBeNull();});
it('reveals university name and city when starting a new KOC',async()=>{render(createElement(LeadApplicationForm));await screen.findByText('Test Campus · Inactive');fireEvent.click(screen.getByLabelText('Start a KOC at a new university'));expect(screen.getByLabelText('University name')).toBeTruthy();expect(screen.getByLabelText('University city')).toBeTruthy();expect(screen.queryByLabelText('University')).toBeNull();});

it('reviews and submits a new university without selecting an existing campus',async()=>{
 render(createElement(LeadApplicationForm));await screen.findByText('Test Campus · Inactive');fireEvent.click(screen.getByLabelText('Start a KOC at a new university'));
 for(const [label,value] of [['Full name','Campus Applicant'],['Username','new_campus_lead'],['Password','long-password-123'],['Course','History'],['University name','New Test University'],['University city','Test City'],['Why would you like to lead a KOC?','I want to support our campus community.'],['Your leadership or fellowship experience','I have helped organise campus prayer meetings.'],['Your availability','Tuesday afternoons'],['Your plan for the campus','I will meet students and organise weekly fellowship.']] as const)fireEvent.change(screen.getByLabelText(new RegExp('^'+label.replace('?','\\?'))),{target:{value}});
 fireEvent.click(screen.getByText('Review application'));await screen.findByRole('heading',{name:'Review your application'});expect(screen.getByText('New Test University, Test City')).toBeTruthy();fireEvent.click(screen.getByText('Submit application'));await screen.findByRole('heading',{name:'Application received'});expect(mocks.submit.mock.calls[0][0]).toEqual(expect.objectContaining({kind:'new',campusId:null,newUniversityName:'New Test University',newUniversityCity:'Test City'}));
});

it('preserves answers when editing and replaces the request ID for a changed application',async()=>{
 mocks.submit.mockRejectedValue(new Error('Your application could not be submitted.'));render(createElement(LeadApplicationForm));await fill();fireEvent.click(screen.getByText('Review application'));await screen.findByText('Submit application');fireEvent.click(screen.getByText('Submit application'));await screen.findByRole('alert');const first=mocks.submit.mock.calls[0][0].requestId;
 fireEvent.click(screen.getByText('Edit application'));expect((screen.getByLabelText(/^Username/) as HTMLInputElement).value).toBe('campus_applicant');fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'Updated Applicant'}});fireEvent.click(screen.getByText('Review application'));await screen.findByText('Updated Applicant');fireEvent.click(screen.getByText('Submit application'));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledTimes(2));expect(mocks.submit.mock.calls[1][0].requestId).not.toBe(first);
});
