import {describe,it,expect,vi} from 'vitest';
import {createPageHandler} from '../supabase/functions/protected-material-page/handler';
const material='11111111-1111-1111-1111-111111111111';
const session='22222222-2222-2222-2222-222222222222';
function setup(){const deps={authenticate:vi.fn().mockResolvedValue(true),access:vi.fn().mockResolvedValue({session_id:session,object_path:'private/page-1.png',watermark_identity:'Actual User | user@example.test',page_count:3}),download:vi.fn().mockResolvedValue(new Uint8Array([1,2,3])),stamp:vi.fn().mockReturnValue(new Uint8Array([4,5,6]))};return {deps,handler:createPageHandler(deps)};}
function request(body:unknown={},token='token'){return new Request('https://test/functions/v1/protected-material-page',{method:'POST',headers:{'Origin':'https://kocm.vercel.app','Authorization':`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});}
describe('protected page delivery',()=>{
 it('rejects unauthenticated callers before any storage access',async()=>{const {deps,handler}=setup();deps.authenticate.mockResolvedValue(false);expect((await handler(request({materialId:material,page:1}))).status).toBe(401);expect(deps.download).not.toHaveBeenCalled();});
 it('uses authorized server paths and baked-in identity, never caller supplied paths or identity',async()=>{const {deps,handler}=setup();const response=await handler(request({materialId:material,page:1,objectPath:'other-campus.pdf',identity:'fake'}));expect(response.status).toBe(200);expect(deps.download).toHaveBeenCalledWith('private/page-1.png');expect(deps.stamp).toHaveBeenCalledWith(expect.any(Uint8Array),'Actual User | user@example.test',expect.stringContaining(session.slice(0,8)));expect([...new Uint8Array(await response.arrayBuffer())]).toEqual([4,5,6]);expect(response.headers.get('Cache-Control')).toContain('no-store');expect(response.headers.get('X-Reader-Session')).toBe(session);});
 it('rejects invalid page numbers and unknown origins',async()=>{const {deps,handler}=setup();expect((await handler(request({materialId:material,page:0}))).status).toBe(400);const req=request({materialId:material,page:1});req.headers.set('Origin','https://untrusted.example');expect((await handler(req)).status).toBe(403);expect(deps.download).not.toHaveBeenCalled();});
 it('fails closed after permission revocation or expired sessions',async()=>{const {deps,handler}=setup();deps.access.mockRejectedValue({code:'42501',message:'Reader session expired. Reopen the material.'});expect((await handler(request({materialId:material,page:1,sessionId:session}))).status).toBe(403);expect(deps.download).not.toHaveBeenCalled();});
 it('does not expose internal exceptions or original file paths',async()=>{const {deps,handler}=setup();deps.download.mockRejectedValue(new Error('bucket original secret.pdf database failure'));const r=await handler(request({materialId:material,page:1}));expect(r.status).toBe(503);expect(await r.text()).not.toContain('secret');});
 it('limits request size and rejects anonymous requests without JWT',async()=>{const {deps,handler}=setup();expect((await handler(request({materialId:material,page:1,pad:'x'.repeat(3000)}))).status).toBe(413);const req=request({materialId:material,page:1});req.headers.delete('Authorization');expect((await handler(req)).status).toBe(401);expect(deps.download).not.toHaveBeenCalled();});
});
