import {it,expect,vi} from 'vitest';
import {createUsernameAuthHandler,attachVerifiedEmail,type Signup} from '../supabase/functions/username-auth/handler';
const signup={action:'signup',username:'Campus_Lead',fullName:'Campus Lead',password:'long-test-password',campusId:'11111111-1111-4111-8111-111111111111'};
const req=(body:unknown,key='public')=>new Request('https://test',{method:'POST',headers:{apikey:key,origin:'https://kocm.vercel.app','content-type':'application/json'},body:JSON.stringify(body)});
function setup(){const claim=vi.fn(async()=>true),create=vi.fn(async(input:Signup)=> input.username ? 'user-id' : ''),assign=vi.fn(async()=>{}),remove=vi.fn(async()=>{}),resolve=vi.fn(async()=> 'opaque@accounts.kocm.invalid'),signin=vi.fn(async()=>({access_token:'access',refresh_token:'refresh'}));return {claim,create,assign,remove,resolve,signin,handler:createUsernameAuthHandler({publishableKey:'public',claim,create,assign,remove,resolve,signin})};}
it('creates only pending username accounts through a server generated alias',async()=>{const s=setup();expect(await(await s.handler(req(signup))).json()).toEqual({ok:true});expect(s.create.mock.calls[0][0]).toMatchObject({username:'campus_lead',fullName:'Campus Lead'});expect(s.assign).toHaveBeenCalledWith('user-id','campus_lead',signup.campusId);});
it('rejects bad usernames and short signup passwords before auth creation',async()=>{const s=setup();for(const patch of [{username:'ab'},{username:'admin@example.com'},{password:'short'}])expect((await s.handler(req({...signup,...patch}))).status).toBe(400);expect(s.create).not.toHaveBeenCalled();});
it('rolls back created user when username claim fails',async()=>{const s=setup();s.assign.mockRejectedValue(new Error('duplicate'));expect((await s.handler(req(signup))).status).toBe(400);expect(s.remove).toHaveBeenCalledWith('user-id');});
it('resolves usernames privately and accepts attached real email login',async()=>{const s=setup();expect((await s.handler(req({action:'signin',identifier:'Campus_Lead',password:'password'}))).status).toBe(200);expect(s.resolve).toHaveBeenCalledWith('campus_lead');await s.handler(req({action:'signin',identifier:'Real@Example.org',password:'password'}));expect(s.signin).toHaveBeenLastCalledWith('real@example.org','password');});
it('uses generic sign in errors and blocks unauthorized or throttled callers',async()=>{const s=setup();expect((await s.handler(req(signup,'bad'))).status).toBe(401);s.claim.mockResolvedValue(false);expect((await s.handler(req(signup))).status).toBe(429);expect(s.create).not.toHaveBeenCalled();s.claim.mockResolvedValue(true);s.signin.mockRejectedValue(new Error('sensitive'));const text=await(await s.handler(req({action:'signin',identifier:'campus_lead',password:'password'}))).text();expect(text).not.toContain('sensitive');expect(JSON.parse(text).error).toBe('Unable to sign in with those details.');});

it('rejects oversized body and disallowed origins before sensitive work',async()=>{const s=setup();expect((await s.handler(req({...signup,padding:'x'.repeat(9000)}))).status).toBe(400);const bad=req(signup);bad.headers.set('origin','https://evil.test');expect((await s.handler(bad)).status).toBe(403);expect(s.create).not.toHaveBeenCalled();});

function attachSetup(){const base=setup();const owner=vi.fn(async()=>({id:'owner-id',email:'11111111-1111-4111-8111-111111111111@accounts.kocm.invalid'}));const provePassword=vi.fn(async()=>{});const configured=vi.fn(()=>true),attach=vi.fn(async()=>{});const handler=createUsernameAuthHandler({...base,publishableKey:'public',owner,provePassword,emailConfigured:configured,attach});return {...base,owner,provePassword,configured,attach,handler};}
const attachReq=(patch:Record<string,unknown>={},bearer='owner-jwt')=>{const request=req({action:'attach_email',email:'new@example.org',currentPassword:'current-password',...patch});if(bearer)request.headers.set('authorization',`Bearer ${bearer}`);return request;};
it('attaches email only after owner JWT and current password proof',async()=>{const s=attachSetup();expect(await(await s.handler(attachReq())).json()).toEqual({ok:true,confirmationRequired:true});expect(s.owner).toHaveBeenCalledWith('owner-jwt');expect(s.provePassword).toHaveBeenCalledWith(expect.objectContaining({id:'owner-id'}),'current-password');expect(s.attach).toHaveBeenCalledWith({id:'owner-id',email:'11111111-1111-4111-8111-111111111111@accounts.kocm.invalid'},'new@example.org');});
it('requires owner credentials and rejects changes to existing real addresses',async()=>{const s=attachSetup();expect((await s.handler(attachReq({},''))).status).toBe(401);s.owner.mockRejectedValueOnce(Error('password detail'));expect((await s.handler(attachReq())).status).toBe(401);s.owner.mockResolvedValueOnce({id:'owner-id',email:'real@example.org'});expect((await s.handler(attachReq())).status).toBe(403);expect(s.attach).not.toHaveBeenCalled();});
it('does not mutate identity without configured delivery and validates one real recipient',async()=>{const s=attachSetup();s.configured.mockReturnValue(false);expect((await s.handler(attachReq())).status).toBe(503);expect(s.attach).not.toHaveBeenCalled();for(const email of ['user@accounts.kocm.invalid','person@example.org,other@example.org','person@example.org\r\nBcc:other@example.org'])expect((await s.handler(attachReq({email}))).status).toBe(400);});
it('does not expose confirmation tokens or backend failures',async()=>{const s=attachSetup();s.attach.mockRejectedValueOnce(Error('TOKEN secret'));const response=await s.handler(attachReq());expect(response.status).toBe(503);expect(await response.text()).not.toContain('secret');});

it('generates both confirmation tokens before confirming only alias and delivering new link',async()=>{const events:string[]=[];const owner={id:'owner',email:'alias@accounts.kocm.invalid'};await attachVerifiedEmail(owner,'new@example.org',{verificationEnabled:async()=>true,generate:async(kind)=>{events.push(kind);return {userId:'owner',tokenHash:kind+'hash',actionLink:'https://auth.test/new-link'};},confirmAlias:async hash=>{events.push(hash);},deliver:async(recipient,link)=>{events.push(recipient,link);}});expect(events).toEqual(['email_change_current','email_change_new','email_change_currenthash','new@example.org','https://auth.test/new-link']);});
it('fails closed if project autoconfirms or generated confirmation belongs to another user',async()=>{const generate=vi.fn(async()=>({userId:'other',tokenHash:'secret',actionLink:'secret'}));const confirmAlias=vi.fn(async()=>{}),deliver=vi.fn(async()=>{});const deps={verificationEnabled:async()=>false,generate,confirmAlias,deliver};await expect(attachVerifiedEmail({id:'owner',email:'alias@accounts.kocm.invalid'},'new@example.org',deps)).rejects.toThrow();expect(generate).not.toHaveBeenCalled();deps.verificationEnabled=async()=>true;await expect(attachVerifiedEmail({id:'owner',email:'alias@accounts.kocm.invalid'},'new@example.org',deps)).rejects.toThrow();expect(confirmAlias).not.toHaveBeenCalled();expect(deliver).not.toHaveBeenCalled();});
it('throttles attach attempts before password verification or mutation',async()=>{const s=attachSetup();s.claim.mockResolvedValue(false);expect((await s.handler(attachReq())).status).toBe(429);expect(s.provePassword).not.toHaveBeenCalled();expect(s.attach).not.toHaveBeenCalled();expect(s.claim).toHaveBeenCalledWith(expect.stringMatching(/^[a-f0-9]{64}$/),'attach_email');});
