import {z} from 'zod';
const whole=(max=100000)=>z.preprocess(value=>(typeof value==='string'&&!value.trim())||value===null||value===undefined?undefined:Number(value),z.number({required_error:'Enter a whole number.',invalid_type_error:'Enter a whole number.'}).int().min(0).max(max));
const text=(max=4000)=>z.string().trim().min(1,'This answer is required.').max(max);
export const campusWeeklySchema=z.object({sessionDate:text(10).regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Enter a valid date.'),startTime:text(5).regex(/^([01]\d|2[0-3]):[0-5]\d$/),endTime:text(5).regex(/^([01]\d|2[0-3]):[0-5]\d$/),lesson:text(200).regex(/^(week\s+\d+\s*[:\-–]\s*\S.*|kickback(?:\s.*)?)$/i,'Use Week number: title, or Kickback.'),attendanceExcludingLead:whole(),firstTimers:whole(),bornAgain:whole(),prayerMinutes:whole(1000000),prayerWalk:z.enum(['yes','no']),holyGhostBaptism:z.enum(['yes','no']),tonguesRecipients:whole().optional(),evangelismDatesTimes:text(),evangelismMinutes:whole(1000000),evangelismZeroReason:z.string().trim().max(1000),soulsWon:whole(),contactsTaken:whole(),contactsAttendedFellowship:whole(),homeVisits:whole(),churchAttendeesExcludingCore:whole(),churchAttendeesIncludingCore:whole(),churchFirstTimers:whole(),overallServing:whole(),newDepartmentJoiners:whole(),outreachOutings:whole(10000),incidentNotes:z.string().trim().max(4000),lateReason:z.string().trim().max(1000)}).superRefine((value,ctx)=>{if(value.holyGhostBaptism==='yes'&&value.tonguesRecipients===undefined)ctx.addIssue({code:'custom',path:['tonguesRecipients'],message:'Enter the number who spoke in tongues.'});if(value.evangelismMinutes===0&&!value.evangelismZeroReason)ctx.addIssue({code:'custom',path:['evangelismZeroReason'],message:'Explain why no evangelism took place.'});});
export type CampusWeeklyAnswers=z.output<typeof campusWeeklySchema>;
export function sanitizeCampusWeekly(input:unknown):CampusWeeklyAnswers{const visible=input&&typeof input==='object'&&!Array.isArray(input)?{...input as Record<string,unknown>}:input;if(visible&&typeof visible==='object'&&'holyGhostBaptism' in visible&&visible.holyGhostBaptism==='no')delete (visible as Record<string,unknown>).tonguesRecipients;const answers=campusWeeklySchema.parse(visible);if(answers.holyGhostBaptism==='no')delete answers.tonguesRecipients;if(answers.evangelismMinutes!==0)answers.evangelismZeroReason='';return answers;}
export const campusWeeklySections=[
 {title:'General',fields:[['sessionDate','Session date','date'],['startTime','Start time','time'],['endTime','End time','time'],['lesson','Lesson — Week number: title, or Kickback','text'],['attendanceExcludingLead','Attendance excluding the lead','number'],['firstTimers','First timers','number'],['bornAgain','How many were born again?','number']]},
 {title:'Prayer',fields:[['prayerMinutes','KOC prayer minutes (including core team; exclude general church prayer)','number'],['prayerWalk','Did you do a prayer walk?','yesno'],['holyGhostBaptism','Was anyone baptised in the Holy Ghost?','yesno'],['tonguesRecipients','How many spoke in tongues?','number']]},
 {title:'Evangelism',fields:[['evangelismDatesTimes','Evangelism dates and times','textarea'],['evangelismMinutes','Evangelism minutes','number'],['evangelismZeroReason','Why was there no evangelism this week?','textarea'],['soulsWon','Souls won','number'],['contactsTaken','Contacts taken','number'],['contactsAttendedFellowship','Contacts who attended fellowship','number']]},
 {title:'Church',fields:[['homeVisits','Home visits','number'],['churchAttendeesExcludingCore','Church attendees excluding core team','number'],['churchAttendeesIncludingCore','Church attendees including core team','number'],['churchFirstTimers','Church first timers (exclude Kharis transfers)','number'],['overallServing','Overall people serving in church','number'],['newDepartmentJoiners','New department joiners','number']]},
 {title:'Incidents and platform statistics',fields:[['incidentNotes','Incidents (optional)','textarea'],['outreachOutings','Outreach outings — additional platform statistic','number']]}
] as const;
