-- Public university reference points researched 2026-10-08. Not confirmed KOC venues.
-- Preserve administrator corrections; only fill campuses still missing both coordinates.
-- Bath: https://www.bath.ac.uk/locations/university-of-bath-claverton-down-campus/
update public.campuses set latitude=51.3766938,longitude=-2.3234206,address='University reference point — KOC venue not confirmed. University of Bath, Claverton Down Road, Claverton Down, Bath, Bath and North East Somerset, West of England, England, BA2 7AR, United Kingdom. University source: https://www.bath.ac.uk/locations/university-of-bath-claverton-down-campus/. Coordinate source: https://www.openstreetmap.org/way/345133857' where name='Bath' and latitude is null and longitude is null;
-- Bath Spa: https://www.bathspa.ac.uk/about-us/find-us/
update public.campuses set latitude=51.3748580,longitude=-2.4387146,address='University reference point — KOC venue not confirmed. Bath Spa University, Corston Drive, Bath, Bath and North East Somerset, West of England, England, BA2 9BN, United Kingdom. University source: https://www.bathspa.ac.uk/about-us/find-us/. Coordinate source: https://www.openstreetmap.org/way/266864205' where name='Bath Spa' and latitude is null and longitude is null;
-- Brighton: https://www.brighton.ac.uk/about-us/contact-us/maps/moulsecoomb-campus.aspx
update public.campuses set latitude=50.8455015,longitude=-0.1193272,address='University reference point — KOC venue not confirmed. Heavy Engineering Building, Lewes Road, Hollingdean, Brighton, Brighton and Hove, England, BN2 4GJ, United Kingdom. University source: https://www.brighton.ac.uk/about-us/contact-us/maps/moulsecoomb-campus.aspx. Coordinate source: https://www.openstreetmap.org/way/152821331' where name='Brighton' and latitude is null and longitude is null;
-- Bristol: https://www.bristol.ac.uk/students/your-studies/libraries-study-spaces/study-spaces/senate-house/
update public.campuses set latitude=51.4590260,longitude=-2.6034263,address='University reference point — KOC venue not confirmed. Senate House Student Resource Centre, Tyndall Avenue, Tyndall''s Park, Cotham, Bristol, City of Bristol, West of England, England, BS8 1TH, United Kingdom. University source: https://www.bristol.ac.uk/students/your-studies/libraries-study-spaces/study-spaces/senate-house/. Coordinate source: https://www.openstreetmap.org/way/36991067' where name='Bristol' and latitude is null and longitude is null;
-- Cardiff: https://www.cardiff.ac.uk/visit/accessibility/cathays-park-campus/main-building
update public.campuses set latitude=51.4876934,longitude=-3.1793944,address='University reference point — KOC venue not confirmed. Cardiff University - Main Building, Museum Avenue, Crockherbtown, Civic Centre, Cathays, Cardiff, Cymru / Wales, CF10 3AT, United Kingdom. University source: https://www.cardiff.ac.uk/visit/accessibility/cathays-park-campus/main-building. Coordinate source: https://www.openstreetmap.org/way/56056207' where name='Cardiff' and latitude is null and longitude is null;
-- City of London: https://www.citystgeorges.ac.uk/about/find-contact/find/clerkenwell-campus
update public.campuses set latitude=51.5276574,longitude=-0.1036050,address='University reference point — KOC venue not confirmed. City St George’s, University of London, Northampton Square, St Luke''s, Angel, Clerkenwell, London Borough of Islington, Greater London, England, EC1V 0JA, United Kingdom. University source: https://www.citystgeorges.ac.uk/about/find-contact/find/clerkenwell-campus. Coordinate source: https://www.openstreetmap.org/relation/7608159' where name='City of London' and latitude is null and longitude is null;
-- Cheltenham: https://www.glos.ac.uk/visit-us/our-campuses/francis-close-hall-campus/
update public.campuses set latitude=51.9061009,longitude=-2.0794272,address='University reference point — KOC venue not confirmed. Francis Close Hall, Saint Paul''s Lane, Marle Hill, St Paul’s, Cheltenham, Gloucestershire, England, GL50 4AT, United Kingdom. University source: https://www.glos.ac.uk/visit-us/our-campuses/francis-close-hall-campus/. Coordinate source: https://www.openstreetmap.org/way/130549452' where name='Cheltenham' and latitude is null and longitude is null;
-- Coventry: https://www.coventry.ac.uk/study-at-coventry/parents-and-teachers/information-for-parents-and-guardians/enhancing-your-employability/
update public.campuses set latitude=52.4082898,longitude=-1.5052618,address='University reference point — KOC venue not confirmed. Official university address postcode reference point: CV1 5FB. University source: https://www.coventry.ac.uk/study-at-coventry/parents-and-teachers/information-for-parents-and-guardians/enhancing-your-employability/. Coordinate source: https://nominatim.openstreetmap.org/search?postalcode=CV1%205FB&country=United%20Kingdom&format=jsonv2' where name='Coventry' and latitude is null and longitude is null;
-- Essex: https://www.essex.ac.uk/about/contact
update public.campuses set latitude=51.8773639,longitude=0.9498751,address='University reference point — KOC venue not confirmed. University of Essex, Ballantyne Drive, Hythe, Colchester, Essex, England, CO2 8GL, United Kingdom. University source: https://www.essex.ac.uk/about/contact. Coordinate source: https://www.openstreetmap.org/way/500965418' where name='Essex' and latitude is null and longitude is null;
-- Glenside Campus: https://www.uwe.ac.uk/life/campus-and-facilities/glenside-campus/glenside-campus-map
update public.campuses set latitude=51.4840653,longitude=-2.5431548,address='University reference point — KOC venue not confirmed. University of the West of England (Glenside Campus), Blackberry Hill, Stapleton, Bristol, City of Bristol, West of England, England, BS16 1DD, United Kingdom. University source: https://www.uwe.ac.uk/life/campus-and-facilities/glenside-campus/glenside-campus-map. Coordinate source: https://www.openstreetmap.org/relation/19197032' where name='Glenside Campus' and latitude is null and longitude is null;
-- Greenwich: https://www.gre.ac.uk/about-us/travel/greenwich
update public.campuses set latitude=51.4825423,longitude=-0.0066531,address='University reference point — KOC venue not confirmed. University of Greenwich, Park Row, Greenwich Town Centre, East Greenwich, Royal Borough of Greenwich, Greater London, England, SE10 9LS, United Kingdom. University source: https://www.gre.ac.uk/about-us/travel/greenwich. Coordinate source: https://www.openstreetmap.org/node/243764607' where name='Greenwich' and latitude is null and longitude is null;
-- King’s College: https://www.kcl.ac.uk/visit/strand-campus
update public.campuses set latitude=51.5114753,longitude=-0.1161094,address='University reference point — KOC venue not confirmed. King''s College London, Strand Campus, Strand, St Clement Danes, Covent Garden, City of Westminster, Greater London, England, WC2R 2LS, United Kingdom. University source: https://www.kcl.ac.uk/visit/strand-campus. Coordinate source: https://www.openstreetmap.org/relation/5747097' where name='King’s College' and latitude is null and longitude is null;
-- Medway: https://www.gre.ac.uk/about-us/travel/medway
update public.campuses set latitude=51.3966118,longitude=0.5453869,address='University reference point — KOC venue not confirmed. University of Greenwich/Medway Campus, Purser Way, St. Marys Island, Brompton, Gillingham, Medway, England, ME7 1FG, United Kingdom. University source: https://www.gre.ac.uk/about-us/travel/medway. Coordinate source: https://www.openstreetmap.org/way/507310710' where name='Medway' and latitude is null and longitude is null;
-- Surrey: https://www.surrey.ac.uk/visit-university/how-get-here
update public.campuses set latitude=51.2427483,longitude=-0.5862850,address='University reference point — KOC venue not confirmed. University Of Surrey AX Building, Perimeter Road, University, Stag Hill, Guildford, Surrey, England, GU2 7JW, United Kingdom. University source: https://www.surrey.ac.uk/visit-university/how-get-here. Coordinate source: https://www.openstreetmap.org/node/565759146' where name='Surrey' and latitude is null and longitude is null;
-- Roehampton: https://www.roehampton.ac.uk/student-life/our-campus/
update public.campuses set latitude=51.4485315,longitude=-0.2440107,address='University reference point — KOC venue not confirmed. Roehampton University, Bordon Walk, Ibsley Neighbourhood, Roehampton, London Borough of Wandsworth, Greater London, England, SW15 4JG, United Kingdom. University source: https://www.roehampton.ac.uk/student-life/our-campus/. Coordinate source: https://www.openstreetmap.org/relation/5904595' where name='Roehampton' and latitude is null and longitude is null;
-- University of East London: https://www.uel.ac.uk/about-uel/our-campuses/docklands-campus
update public.campuses set latitude=51.5070870,longitude=0.0708160,address='University reference point — KOC venue not confirmed. University of East London Docklands Campus, Woolwich Manor Way, Gallions Reach, London Borough of Newham, Greater London, England, E16 2AH, United Kingdom. University source: https://www.uel.ac.uk/about-uel/our-campuses/docklands-campus. Coordinate source: https://www.openstreetmap.org/node/4728085314' where name='University of East London' and latitude is null and longitude is null;
-- UOL – Manchester: https://www.law.ac.uk/locations/manchester/
update public.campuses set latitude=53.4803158,longitude=-2.2393912,address='University reference point — KOC venue not confirmed. University of Law, 2, New York Street, Civic Quarter, City Centre, Manchester, Greater Manchester, England, M1 4HJ, United Kingdom. University source: https://www.law.ac.uk/locations/manchester/. Coordinate source: https://www.openstreetmap.org/node/4624319249' where name='UOL – Manchester' and latitude is null and longitude is null;
-- University Of West London: https://lcme.uwl.ac.uk/information/exam-centres-uk-ireland/england/london-ealing-uwl
update public.campuses set latitude=51.5066187,longitude=-0.3035485,address='University reference point — KOC venue not confirmed. Official university address postcode reference point: W5 5RF. University source: https://lcme.uwl.ac.uk/information/exam-centres-uk-ireland/england/london-ealing-uwl. Coordinate source: https://nominatim.openstreetmap.org/search?postalcode=W5%205RF&country=United%20Kingdom&format=jsonv2' where name='University Of West London' and latitude is null and longitude is null;
-- Anglia Ruskin: https://www.aru.ac.uk/student-life/life-on-campus/cambridge-campus/travelling-to-our-cambridge-campus
update public.campuses set latitude=52.2033882,longitude=0.1350226,address='University reference point — KOC venue not confirmed. Anglia Ruskin University (Cambridge Campus), East Road, The Kite, Petersfield, Cambridge, Cambridgeshire, Cambridgeshire and Peterborough, England, CB1 1PT, United Kingdom. University source: https://www.aru.ac.uk/student-life/life-on-campus/cambridge-campus/travelling-to-our-cambridge-campus. Coordinate source: https://www.openstreetmap.org/way/3987047' where name='Anglia Ruskin' and latitude is null and longitude is null;
-- Hertfordshire: https://www.herts.ac.uk/contact-us/where-to-find-us
update public.campuses set latitude=51.752447,longitude=-0.2429534,address='University reference point — KOC venue not confirmed. Official university address postcode reference point: AL10 9AB. University source: https://www.herts.ac.uk/contact-us/where-to-find-us. Coordinate source: https://nominatim.openstreetmap.org/search?postalcode=AL10%209AB&country=United%20Kingdom&format=jsonv2' where name='Hertfordshire' and latitude is null and longitude is null;
-- LSBU: https://www.lsbu.ac.uk/study/study-at-lsbu/open-days/find-us
update public.campuses set latitude=51.4977032,longitude=-0.1018089,address='University reference point — KOC venue not confirmed. London South Bank University, Ontario Street, Elephant and Castle, London Borough of Southwark, Greater London, England, SE1 6NG, United Kingdom. University source: https://www.lsbu.ac.uk/study/study-at-lsbu/open-days/find-us. Coordinate source: https://www.openstreetmap.org/relation/14863884' where name='LSBU' and latitude is null and longitude is null;
-- Middlesex: https://www.mdx.ac.uk/about-us/get-in-touch/
update public.campuses set latitude=51.5896303,longitude=-0.2279502,address='University reference point — KOC venue not confirmed. Middlesex University, The Burroughs, The Hyde, Hendon, London Borough of Barnet, Greater London, England, NW4 4HE, United Kingdom. University source: https://www.mdx.ac.uk/about-us/get-in-touch/. Coordinate source: https://www.openstreetmap.org/node/469767102' where name='Middlesex' and latitude is null and longitude is null;
-- Ravensbourne: https://www.ravensbourne.ac.uk/about-us/location
update public.campuses set latitude=51.5016582,longitude=0.0057045,address='University reference point — KOC venue not confirmed. Ravensbourne University London, 6, Penrose Way, Greenwich Peninsula, Royal Borough of Greenwich, Greater London, England, SE10 0EW, United Kingdom. University source: https://www.ravensbourne.ac.uk/about-us/location. Coordinate source: https://www.openstreetmap.org/way/151942966' where name='Ravensbourne' and latitude is null and longitude is null;
-- Royal Holloway: https://www.royalholloway.ac.uk/about-us/more/how-to-find-us/
update public.campuses set latitude=51.4244496,longitude=-0.5642554,address='University reference point — KOC venue not confirmed. Royal Holloway, Egham Hill, Englefield Green, Runnymede, Surrey, England, TW20 0RL, United Kingdom. University source: https://www.royalholloway.ac.uk/about-us/more/how-to-find-us/. Coordinate source: https://www.openstreetmap.org/way/4527679' where name='Royal Holloway' and latitude is null and longitude is null;

-- Audit correction: use documented primary campus reference points instead of unrelated geocoder matches.
-- Only correct unchanged migration-generated coordinates/address with no administrator meeting details.
update public.campuses set latitude=51.2796400,longitude=1.0893600,
 address='University reference point — KOC venue not confirmed. Canterbury Christ Church University, North Holmes Road, Canterbury CT1 1QU (official address postcode reference point). University source: https://www.canterbury.ac.uk/contact-cccu. Coordinate source: https://nominatim.openstreetmap.org/search?postalcode=CT1%201QU&country=United%20Kingdom&format=jsonv2'
where name='CCCU' and latitude=51.2758755 and longitude=1.0922292
 and address like '%Source: https://www.openstreetmap.org/way/1334491169%' and meeting_info='';
update public.campuses set latitude=52.5875301,longitude=-2.1273864,
 address='University reference point — KOC venue not confirmed. University of Wolverhampton City Campus, Wulfruna Building, Wulfruna Street WV1 1RD. University source: https://www.wlv.ac.uk/about-us/contacts-and-maps/all-maps-and-directions/. Coordinate source: https://www.openstreetmap.org/way/294789924'
where name='Wolverhampton' and latitude=52.5901648 and longitude=-2.1277808
 and address like '%Source: https://www.openstreetmap.org/way/684848398%' and meeting_info='';
