-- University campus reference points, not confirmed KOC meeting venues. Multi-site and ambiguous entries omitted.
-- © OpenStreetMap contributors, ODbL 1.0 https://www.openstreetmap.org/copyright
-- Research date: 2026-10-05
-- Existing pins and meeting information are preserved.
-- Aston: https://www.openstreetmap.org/way/45010066
update public.campuses set latitude = 52.4861905, longitude = -1.8884689, address = 'University campus reference point — KOC meeting location not confirmed. Aston University, Corporation Street, Digbeth, Birmingham, West Midlands, England, B4 7DP, United Kingdom. Source: https://www.openstreetmap.org/way/45010066' where name = 'Aston' and latitude is null and longitude is null;
-- Birmingham City: https://www.openstreetmap.org/way/1102893551
update public.campuses set latitude = 52.4850115, longitude = -1.8838558, address = 'University campus reference point — KOC meeting location not confirmed. Birmingham City University, Belmont Row, Vauxhall, Birmingham, West Midlands, England, B4 7BD, United Kingdom. Source: https://www.openstreetmap.org/way/1102893551' where name = 'Birmingham City' and latitude is null and longitude is null;
-- Bournemouth: https://www.openstreetmap.org/way/100293078
update public.campuses set latitude = 50.7420913, longitude = -1.894164, address = 'University campus reference point — KOC meeting location not confirmed. Bournemouth University (Talbot Campus), White Farm Close, Talbot Woods, Bournemouth, Talbot Village, Bournemouth, Christchurch and Poole, England, BH10 4HX, United Kingdom. Source: https://www.openstreetmap.org/way/100293078' where name = 'Bournemouth' and latitude is null and longitude is null;
-- Brunel: https://www.openstreetmap.org/relation/12968920
update public.campuses set latitude = 51.5326092, longitude = -0.4740499, address = 'University campus reference point — KOC meeting location not confirmed. Brunel University of London, Penn Close, Cowley, Uxbridge, Greater London, England, UB8 3PH, United Kingdom. Source: https://www.openstreetmap.org/relation/12968920' where name = 'Brunel' and latitude is null and longitude is null;
-- CCCU: https://www.openstreetmap.org/way/1334491169
update public.campuses set latitude = 51.2758755, longitude = 1.0922292, address = 'University campus reference point — KOC meeting location not confirmed. Canterbury Christ Church University, Canterbury College Access Road, Stuppington, Longport, Canterbury, Kent, England, CT1 1PH, United Kingdom. Source: https://www.openstreetmap.org/way/1334491169' where name = 'CCCU' and latitude is null and longitude is null;
-- DMU: https://www.openstreetmap.org/relation/18997971
update public.campuses set latitude = 52.6297131, longitude = -1.139284, address = 'University campus reference point — KOC meeting location not confirmed. De Montfort University, Western Boulevard, Bede Island, Leicester, City of Leicester, England, LE2 7EW, United Kingdom. Source: https://www.openstreetmap.org/relation/18997971' where name = 'DMU' and latitude is null and longitude is null;
-- Derby: https://www.openstreetmap.org/way/87690264
update public.campuses set latitude = 52.9379547, longitude = -1.4979991, address = 'University campus reference point — KOC meeting location not confirmed. University of Derby, Kedleston Road, Markeaton, Derby, East Midlands, England, DE22 1GB, United Kingdom. Source: https://www.openstreetmap.org/way/87690264' where name = 'Derby' and latitude is null and longitude is null;
-- Exeter: https://www.openstreetmap.org/node/12526675177
update public.campuses set latitude = 50.7357007, longitude = -3.5308775, address = 'University campus reference point — KOC meeting location not confirmed. University of Exeter Streatham Court, Prince Of Wales Road, Pennsylvania, Exeter, Devon, Devon and Torbay, England, EX4 4PU, United Kingdom. Source: https://www.openstreetmap.org/node/12526675177' where name = 'Exeter' and latitude is null and longitude is null;
-- Kingston: https://www.openstreetmap.org/way/22498760
update public.campuses set latitude = 51.4030739, longitude = -0.3032181, address = 'University campus reference point — KOC meeting location not confirmed. Kingston University Penrhyn Road Campus, Penrhyn Road, Surbiton, Kingston upon Thames, Greater London, England, KT1 2EE, United Kingdom. Source: https://www.openstreetmap.org/way/22498760' where name = 'Kingston' and latitude is null and longitude is null;
-- Leicester: https://www.openstreetmap.org/relation/18370966
update public.campuses set latitude = 52.6216953, longitude = -1.1246946, address = 'University campus reference point — KOC meeting location not confirmed. University of Leicester Central Campus, Tigers Way, Highfields, Leicester, City of Leicester, England, LE1 6YU, United Kingdom. Source: https://www.openstreetmap.org/relation/18370966' where name = 'Leicester' and latitude is null and longitude is null;
-- Liverpool: https://www.openstreetmap.org/relation/19980323
update public.campuses set latitude = 53.4072429, longitude = -2.9658326, address = 'University campus reference point — KOC meeting location not confirmed. University of Liverpool, Pembroke Street, Knowledge Quarter, Edge Hill, Liverpool, Liverpool City Region, England, L69 3GS, United Kingdom. Source: https://www.openstreetmap.org/relation/19980323' where name = 'Liverpool' and latitude is null and longitude is null;
-- Loughborough: https://www.openstreetmap.org/way/9961576
update public.campuses set latitude = 52.763845, longitude = -1.2372582, address = 'University campus reference point — KOC meeting location not confirmed. Loughborough University, Union Way, Thorpe Acre, Loughborough, Charnwood, Leicestershire, England, LE11 3TR, United Kingdom. Source: https://www.openstreetmap.org/way/9961576' where name = 'Loughborough' and latitude is null and longitude is null;
-- Northampton: https://www.openstreetmap.org/way/462803418
update public.campuses set latitude = 52.2305816, longitude = -0.8869153, address = 'University campus reference point — KOC meeting location not confirmed. University of Northampton Waterside Campus, Dun Mills Road, Far Cotton and Delapre, Northampton, West Northamptonshire, England, NN1 5PH, United Kingdom. Source: https://www.openstreetmap.org/way/462803418' where name = 'Northampton' and latitude is null and longitude is null;
-- Nottingham Trent: https://www.openstreetmap.org/relation/3721676
update public.campuses set latitude = 52.9581456, longitude = -1.1545502, address = 'University campus reference point — KOC meeting location not confirmed. Nottingham Trent University, Chaucer Court, Hockley, The Park, City of Nottingham, East Midlands, England, NG1 5LP, United Kingdom. Source: https://www.openstreetmap.org/relation/3721676' where name = 'Nottingham Trent' and latitude is null and longitude is null;
-- Oxford Brookes: https://www.openstreetmap.org/relation/18312363
update public.campuses set latitude = 51.755223, longitude = -1.230104, address = 'University campus reference point — KOC meeting location not confirmed. Oxford Brookes University Headington Campus, Pullens Lane, Headington Hill, Headington, Oxford, Oxfordshire, England, OX3 0BN, United Kingdom. Source: https://www.openstreetmap.org/relation/18312363' where name = 'Oxford Brookes' and latitude is null and longitude is null;
-- Portsmouth: https://www.openstreetmap.org/way/40600638
update public.campuses set latitude = 50.795245, longitude = -1.0935529, address = 'University campus reference point — KOC meeting location not confirmed. University House, Waltham Street, Somers Town, Portsmouth, England, PO1 2UP, United Kingdom. Source: https://www.openstreetmap.org/way/40600638' where name = 'Portsmouth' and latitude is null and longitude is null;
-- QMUL: https://www.openstreetmap.org/relation/16416944
update public.campuses set latitude = 51.5247403, longitude = -0.0393136, address = 'University campus reference point — KOC meeting location not confirmed. Queen Mary University of London, 327, Mile End Road, Stepney, London Borough of Tower Hamlets, Greater London, England, E1 4NS, United Kingdom. Source: https://www.openstreetmap.org/relation/16416944' where name = 'QMUL' and latitude is null and longitude is null;
-- Reading: https://www.openstreetmap.org/relation/18353143
update public.campuses set latitude = 51.4404358, longitude = -0.9417618, address = 'University campus reference point — KOC meeting location not confirmed. University of Reading - Whiteknights Campus, Pepper Lane, Whitley, Reading, England, RG2 7DN, United Kingdom. Source: https://www.openstreetmap.org/relation/18353143' where name = 'Reading' and latitude is null and longitude is null;
-- UKC: https://www.openstreetmap.org/way/168566667
update public.campuses set latitude = 51.2950874, longitude = 1.0673313, address = 'University campus reference point — KOC meeting location not confirmed. University of Kent, Crab and Winkle Way, St. Dunstan''s, Rough Common, Canterbury, Kent, England, CT2 7FL, United Kingdom. Source: https://www.openstreetmap.org/way/168566667' where name = 'UKC' and latitude is null and longitude is null;
-- UWE: https://www.openstreetmap.org/way/23482197
update public.campuses set latitude = 51.5007679, longitude = -2.5503106, address = 'University campus reference point — KOC meeting location not confirmed. University of the West of England (Frenchay Campus), Coldharbour Lane, Stoke Park, Stoke Park and Cheswick, Harry Stoke, Bristol, South Gloucestershire, West of England, England, BS16 1QY, United Kingdom. Source: https://www.openstreetmap.org/way/23482197' where name = 'UWE' and latitude is null and longitude is null;
-- University of Birmingham: https://www.openstreetmap.org/relation/1972822
update public.campuses set latitude = 52.4504333, longitude = -1.9320033, address = 'University campus reference point — KOC meeting location not confirmed. University of Birmingham Edgbaston Campus, New Fosse Way, Selly Oak, Metchley, Birmingham, West Midlands, England, B29 6TH, United Kingdom. Source: https://www.openstreetmap.org/relation/1972822' where name = 'University of Birmingham' and latitude is null and longitude is null;
-- University of Nottingham: https://www.openstreetmap.org/way/16478993
update public.campuses set latitude = 52.9387428, longitude = -1.2002957, address = 'University campus reference point — KOC meeting location not confirmed. University of Nottingham, University Boulevard, Dunkirk, City of Nottingham, East Midlands, England, NG7 2RD, United Kingdom. Source: https://www.openstreetmap.org/way/16478993' where name = 'University of Nottingham' and latitude is null and longitude is null;
-- Warwick: https://www.openstreetmap.org/relation/2437023
update public.campuses set latitude = 52.3813073, longitude = -1.5639569, address = 'University campus reference point — KOC meeting location not confirmed. University of Warwick, Gibbet Hill Road, Gibbet Hill, Coventry, West Midlands, England, CV4 7FD, United Kingdom. Source: https://www.openstreetmap.org/relation/2437023' where name = 'Warwick' and latitude is null and longitude is null;
-- Wolverhampton: https://www.openstreetmap.org/way/684848398
update public.campuses set latitude = 52.5901648, longitude = -2.1277808, address = 'University campus reference point — KOC meeting location not confirmed. University of Wolverhampton, Red Hill Street, Springfield, Heath Town, Park Village, Wolverhampton, West Midlands, England, WV1 1RN, United Kingdom. Source: https://www.openstreetmap.org/way/684848398' where name = 'Wolverhampton' and latitude is null and longitude is null;
