'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,RefreshCw,Search} from 'lucide-react';
import {listCampuses,friendly,type Campus,type Profile} from '@/lib/koc';
import {formatDate,hours,type Season} from '@/lib/reporting';
import {academicMetrics,buildAcademicAnalytics,compareAcademicAnalytics,type AcademicMetric,type AcademicPeriod,type AcademicSummary,type AcademicTrend} from '@/lib/academic-analytics';
import {loadAcademicAnalyticsData,type AcademicAnalyticsData} from '@/lib/academic-analytics-data';
import {historicalReviewNote,type HistoricalReviewData} from '@/lib/historical-review';
import type {Jump} from '../dashboard';
import './admin-academic-overview.css';
const core:AcademicMetric[]=['attendance','prayerMinutes','evangelismMinutes','outreachOutings'];
const metricName=(metric:AcademicMetric)=>metric==='prayerMinutes'?'Prayer time':metric==='evangelismMinutes'?'Evangelism time':academicMetrics[metric];
const value=(metric:AcademicMetric,amount:number|null|undefined)=>amount==null?'—':metric==='prayerMinutes'||metric==='evangelismMinutes'?hours(Math.round(amount)):amount.toLocaleString('en-GB',{maximumFractionDigits:1});
const coverage=(summary:AcademicSummary)=>summary.coverage===null?'Not started':`${Math.round(summary.coverage*100)}%`;
const chartValue=(metric:AcademicMetric,amount:number|null|undefined)=>amount==null?null:metric==='prayerMinutes'||metric==='evangelismMinutes'?amount/60:amount;
type AlignedTrend={index:number;label:string;current:AcademicTrend|null;previous:AcademicTrend|null};
function AcademicTrendChart({rows,metric,currentName,previousName}:{rows:AlignedTrend[];metric:AcademicMetric;currentName:string;previousName:string|null}){
 const plotted=rows.map(row=>({label:row.label,current:chartValue(metric,row.current?.totals[metric]),previous:chartValue(metric,row.previous?.totals[metric])})),max=Math.max(1,...plotted.flatMap(row=>[row.current??0,row.previous??0]));
 const x=(index:number)=>46+(plotted.length<2?320:index/(plotted.length-1)*650),y=(n:number)=>210-n/max*165;
 function path(key:'current'|'previous'){let active=false;return plotted.map((point,index)=>{const n=point[key];if(n===null){active=false;return '';}const step=`${active?'L':'M'}${x(index).toFixed(2)},${y(n).toFixed(2)}`;active=true;return step;}).join(' ');}
 return <><div className="academic-chart-legend"><span><i/>{currentName}</span>{previousName&&<span><i className="previous"/>{previousName}</span>}</div><svg viewBox="0 0 730 255" role="img" aria-label={`Academic-week trend: ${metricName(metric)}`} className="academic-trend-chart"><title>{metricName(metric)} by aligned academic week. Gaps mean no recorded value.</title>{[0,.25,.5,.75,1].map(ratio=><g key={ratio}><line x1="46" x2="696" y1={y(ratio*max)} y2={y(ratio*max)} className="academic-chart-grid"/><text x="35" y={y(ratio*max)+4} textAnchor="end">{(ratio*max).toLocaleString('en-GB',{maximumFractionDigits:1})}</text></g>)}{previousName&&<path d={path('previous')} className="academic-chart-line previous"/>}<path d={path('current')} className="academic-chart-line"/>{plotted.map((point,index)=>point.current!==null?<circle key={index} cx={x(index)} cy={y(point.current)} r="3" className="academic-chart-point"><title>{point.label}: {point.current}</title></circle>:null)}{plotted.map((point,index)=>(index===0||index===plotted.length-1||index===Math.floor(plotted.length/2))?<text key={index} x={x(index)} y="238" textAnchor="middle">{point.label}</text>:null)}</svg><details className="academic-chart-data"><summary>View weekly values</summary><div className="academic-table-scroll"><table><thead><tr><th>Academic week</th><th>{currentName}</th>{previousName&&<th>{previousName}</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.index}><th>{row.label}</th><td>{value(metric,row.current?.totals[metric])}</td>{previousName&&<td>{value(metric,row.previous?.totals[metric])}</td>}</tr>)}</tbody></table></div></details></>;
}
export default function AdminAcademicOverview({season,profile,jump}:{season:Season;profile:Profile;jump:Jump}){
 const [data,setData]=useState<AcademicAnalyticsData|null>(null),[campuses,setCampuses]=useState<Campus[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[year,setYear]=useState(season.id),[compareYear,setCompareYear]=useState(''),[period,setPeriod]=useState<AcademicPeriod>('full'),[metric,setMetric]=useState<AcademicMetric>('attendance'),[tableMetric,setTableMetric]=useState<AcademicMetric>('attendance'),[group,setGroup]=useState<'campus'|'region'>('campus'),[average,setAverage]=useState(false),[query,setQuery]=useState('');
 async function refresh(){setLoading(true);setError('');setData(null);try{const [loaded,active]=await Promise.all([loadAcademicAnalyticsData(),listCampuses()]);setData(loaded);setCampuses(active);}catch(e){setError(friendly(e));}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;Promise.all([loadAcademicAnalyticsData(),listCampuses()]).then(([loaded,active])=>{if(alive){setData(loaded);setCampuses(active);}}).catch(e=>{if(alive){setError(friendly(e));setData(null);}}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 const selected=data?.seasons.find(row=>row.id===year)??data?.seasons.find(row=>row.id===season.id)??data?.seasons.at(-1),compared=data?.seasons.find(row=>row.id===compareYear&&row.id!==selected?.id);
 const current=useMemo(()=>selected&&data?buildAcademicAnalytics({season:selected,campuses,reports:data.reports,feedback:data.feedback,period}):null,[selected,data,campuses,period]);
 const previous=useMemo(()=>compared&&data?buildAcademicAnalytics({season:compared,campuses,reports:data.reports,feedback:data.feedback,period}):null,[compared,data,campuses,period]);
 const comparison=current&&previous?compareAcademicAnalytics(current,previous):null;
 const aligned=current?previous?comparison!.weekly:current.weekly.map((row,index)=>({index:index+1,label:row.label,current:row,previous:null})):[];
 if(error)return <p className="management-alert" role="alert">{error}</p>;
 if(loading||!data)return <p role="status" className="loading-line">Loading academic-year statistics…</p>;
 if(!current||!selected)return <section className="panel padded"><h1>Academic-year overview</h1><p className="muted">No reporting academic years are available yet.</p></section>;
 const partial=current.elapsedEndDate<current.endDate,metrics=Object.keys(academicMetrics) as AcademicMetric[],rows=group==='campus'?current.campuses.map(row=>({...row,label:row.campusName})):current.regions.map(row=>({...row,label:row.region})),visible=rows.filter(row=>`${row.label} ${'region' in row?row.region:''}`.toLowerCase().includes(query.trim().toLowerCase())),missing=current.campuses.filter(row=>row.missingWeeks>0);
 return <div className="academic-overview">
  <div className="page-heading"><div><div className="eyebrow">LEADERSHIP · ACADEMIC ANALYTICS</div><h1>Academic-year overview</h1><p>{profile.full_name}, review campus activity, full feedback and reporting coverage.</p></div><div className="academic-heading-actions"><button className="button" onClick={refresh}><RefreshCw size={16}/>Refresh</button><button className="button button-yellow" onClick={()=>jump('enter')}>Weekly report<ArrowRight size={16}/></button></div></div>
  <section className="academic-controls" aria-label="Academic-year reporting period"><label>Academic year<select value={selected.id} onChange={event=>{setYear(event.target.value);if(compareYear===event.target.value)setCompareYear('');}}>{data.seasons.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><div className="academic-segment" aria-label="Reporting period"><button aria-pressed={period==='midyear'} onClick={()=>setPeriod('midyear')}>Mid-year · 31 Jan</button><button aria-pressed={period==='full'} onClick={()=>setPeriod('full')}>End-of-year</button></div><label>Compare academic year<select value={compareYear} onChange={event=>setCompareYear(event.target.value)}><option value="">No comparison</option>{data.seasons.filter(row=>row.id!==selected.id).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></section>
  {data.seasons.length===1&&<p className="academic-data-note">Only {selected.name} is available in live reporting. The separate 2023–2024 review reference appears below.</p>}
  <div className="academic-period-note"><span>{formatDate(current.startDate)} – {formatDate(current.endDate)}</span><span>{current.campuses.length} active campuses · {current.overall.submittedWeeks} submitted campus-weeks</span></div>
  {partial&&<p className="academic-window-note">This academic period is in progress. Activity is recorded through {formatDate(current.elapsedEndDate)}; future weeks are excluded. Comparisons align academic weeks, and completed years may contain more weeks.</p>}
  <section className="academic-stat-row" aria-label="Academic-year activity totals">{core.map(key=><div key={key}><span>{metricName(key)}</span><strong>{value(key,current.overall.totals[key])}</strong><small>{current.overall.totals[key]===null?'No recorded activity':`${value(key,current.overall.averages[key])} / submitted campus-week`}</small></div>)}</section>
  <div className="academic-charts-layout"><section className="panel padded academic-trend-panel"><div className="panel-heading"><div><h2>Activity across the academic year</h2><p>Aligned by academic week · gaps are unknown, never zero.</p></div><label className="academic-small-select">Trend metric<select aria-label="Trend metric" value={metric} onChange={event=>setMetric(event.target.value as AcademicMetric)}>{metrics.map(key=><option key={key} value={key}>{metricName(key)}</option>)}</select></label></div>{current.weekly.some(row=>row.totals[metric]!==null)||previous?.weekly.some(row=>row.totals[metric]!==null)?<AcademicTrendChart rows={aligned} metric={metric} currentName={selected.name} previousName={compared?.name??null}/>:<div className="academic-empty"><h3>No submitted activity for this period.</h3><p>Choose another year or review outstanding campus reports.</p></div>}<p className="academic-data-note">{metric==='prayerMinutes'||metric==='evangelismMinutes'?'Chart values are hours. ':''}Totals reflect recorded submissions. Campus coverage can differ between years.</p></section>
  <section className="panel padded academic-coverage"><div className="eyebrow">REPORTING COVERAGE</div><h2>{coverage(current.overall)}</h2><p>{current.overall.submittedWeeks} of {current.overall.expectedWeeks} opened campus-week reports submitted.</p><div className="academic-coverage-track" role="progressbar" aria-label="Submitted report coverage" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round((current.overall.coverage??0)*100)}><span style={{width:`${Math.round((current.overall.coverage??0)*100)}%`}}/></div><dl><dt>Overdue missing reports</dt><dd>{current.overall.missingDueWeeks??0}</dd><dt>Still within deadline</dt><dd>{current.overall.pendingWeeks??0}</dd><dt>Active campuses</dt><dd>{current.campuses.length}</dd></dl><p className="academic-data-note">Opened weeks still within their deadline appear separately from overdue reports. Inactive and in-process campuses are excluded.</p><button className="text-button" onClick={()=>jump('notifications')}>Review reporting alerts<ArrowRight size={15}/></button></section></div>
  <section className="panel padded academic-feedback"><div className="panel-heading"><div><h2>Campus feedback outcomes</h2><p>Recorded through the full weekly feedback form. Legacy reports leave these fields unknown.</p></div></div><div className="academic-feedback-grid">{metrics.filter(key=>!core.includes(key)).map(key=><div key={key}><span>{metricName(key)}</span><strong>{value(key,current.overall.totals[key])}</strong><small>{current.overall.observedWeeks[key]??0} observed campus-weeks</small></div>)}</div></section>
  <section className="panel padded academic-campus-table" aria-label="Campus and cluster activity"><div className="panel-heading"><div><h2>Campus and cluster activity</h2><p>{average?'Average per submitted campus-week':'Recorded totals for the selected period'}</p></div><div className="academic-segment"><button aria-pressed={!average} onClick={()=>setAverage(false)}>Totals</button><button aria-pressed={average} onClick={()=>setAverage(true)}>Weekly averages</button></div></div><div className="academic-table-controls"><label>Group table by<select value={group} onChange={event=>setGroup(event.target.value as 'campus'|'region')}><option value="campus">Campus</option><option value="region">Cluster / region</option></select></label><label>Table metric<select value={tableMetric} onChange={event=>setTableMetric(event.target.value as AcademicMetric)}>{metrics.map(key=><option key={key} value={key}>{metricName(key)}</option>)}</select></label><label className="academic-search"><Search size={16}/><input type="search" aria-label="Search academic activity table" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search campus or cluster"/></label></div><div className="academic-table-scroll"><table><thead><tr><th>{group==='campus'?'Campus':'Cluster / region'}</th>{group==='campus'&&<th>Cluster / region</th>}<th>{metricName(tableMetric)}</th><th>Observed weeks</th><th>Reports</th><th>Coverage</th></tr></thead><tbody>{visible.map(row=><tr key={row.label}><th>{'campusId' in row&&typeof row.campusId==='string'?<button onClick={()=>jump('campus',{campusId:row.campusId as string})}>{row.label}</button>:row.label}</th>{group==='campus'&&<td>{row.region}</td>}<td>{value(tableMetric,average?row.averages[tableMetric]:row.totals[tableMetric])}</td><td>{row.observedWeeks[tableMetric]??0}</td><td>{row.submittedWeeks} / {row.expectedWeeks}</td><td>{coverage(row)}</td></tr>)}</tbody></table></div>{!visible.length&&<p className="muted small">No campuses match your search.</p>}<p className="academic-data-note">Averages use only submissions where this metric was recorded. Observed weeks are campus-weeks, so cluster averages describe an average reporting campus rather than a whole-cluster weekly total.</p></section>
  <section className="panel padded academic-missing"><div className="panel-heading"><div><h2>Campuses with missing reports</h2><p>Open a campus to review its weekly reporting history.</p></div></div>{missing.length?<ul>{missing.map(row=><li key={row.campusId}><span><strong>{row.campusName}</strong><small>{row.region} · {row.missingDueWeeks??0} overdue · {row.pendingWeeks??0} still within deadline</small></span><button aria-label={`Review missing reports for ${row.campusName}`} className="button" onClick={()=>jump('campus',{campusId:row.campusId})}>Review reports<ArrowRight size={15}/></button></li>)}</ul>:<p className="muted small">No opened campus-week reports are missing in this period.</p>}</section>
  <HistoricalReviewReference review={data.historicalReview}/>

 </div>;
}

function HistoricalReviewReference({review}:{review:HistoricalReviewData|null|undefined}){
 const historicalReviewRows=review?.rows??[],historicalReviewOverall=review?.overall??[],historicalAttendanceTrend=review?.attendanceTrend??[];
 const [metric,setMetric]=useState<'attendance'|'prayerHours'|'evangelismHours'>('attendance');
 const label=metric==='attendance'?'Attendance':metric==='prayerHours'?'Prayer hours':'Evangelism hours',max=Math.max(1,...historicalAttendanceTrend.flatMap(row=>[row[2023],row[2024]])),x=(index:number)=>46+index/Math.max(1,historicalAttendanceTrend.length-1)*650,y=(amount:number)=>210-amount/max*165;
 const line=(year:2023|2024)=>historicalAttendanceTrend.map((row,index)=>`${index?'L':'M'}${x(index)},${y(row[year])}`).join(' ');
 if(!historicalReviewRows.length&&!historicalReviewOverall.length&&!historicalAttendanceTrend.length)return <details className="panel padded academic-history"><summary>2023–2024 review reference</summary><p>No historical review data is available for this account.</p></details>;
 return <details open className="panel padded academic-history"><summary>2023–2024 review reference</summary><p>{historicalReviewNote}</p><div className="academic-table-scroll"><table><caption>Overall figures printed in the review</caption><thead><tr><th>Metric</th><th>2023</th><th>2024</th><th>Source page</th></tr></thead><tbody>{historicalReviewOverall.map(row=><tr key={row.metric}><th>{row.metric}<small>{row.unit}</small></th><td>{row[2023]}</td><td>{row[2024]}</td><td>{row.page}</td></tr>)}</tbody></table></div>
  <div className="academic-history-trend"><h3>Published autumn attendance comparison</h3><p className="academic-data-note">Week labels are reproduced from the review; calendar dates and reporting coverage are not supplied.</p><div className="academic-chart-legend"><span><i/>2024 review</span><span><i className="previous"/>2023 review</span></div><svg viewBox="0 0 730 255" role="img" aria-label="Historical attendance comparison for 2023 and 2024" className="academic-trend-chart">{[0,.5,1].map(ratio=><g key={ratio}><line x1="46" x2="696" y1={y(ratio*max)} y2={y(ratio*max)} className="academic-chart-grid"/><text x="35" y={y(ratio*max)+4} textAnchor="end">{Math.round(ratio*max)}</text></g>)}<path d={line(2023)} className="academic-chart-line previous"/><path d={line(2024)} className="academic-chart-line"/>{historicalAttendanceTrend.map((row,index)=>(index===0||index===historicalAttendanceTrend.length-1||index===Math.floor(historicalAttendanceTrend.length/2))?<text key={row.week} x={x(index)} y="238" textAnchor="middle">{row.week}</text>:null)}</svg><details className="academic-chart-data"><summary>View published weekly attendance</summary><div className="academic-table-scroll"><table><thead><tr><th>Published week</th><th>2023</th><th>2024</th></tr></thead><tbody>{historicalAttendanceTrend.map(row=><tr key={row.week}><th>{row.week}</th><td>{row[2023]}</td><td>{row[2024]}</td></tr>)}</tbody></table></div></details></div>
  <div className="academic-history-heading"><h3>Historical campus weekly averages</h3><label className="academic-small-select">Reference metric<select value={metric} onChange={event=>setMetric(event.target.value as typeof metric)}><option value="attendance">Attendance</option><option value="prayerHours">Prayer hours</option><option value="evangelismHours">Evangelism hours</option></select></label></div><div className="academic-table-scroll"><table><thead><tr><th>Historical campus</th><th>Region</th><th>{label} 2023</th><th>{label} 2024</th></tr></thead><tbody>{historicalReviewRows.map(row=><tr key={row.campusName}><th>{row.campusName}<small>Historical reference · page {row.page}</small></th><td>{row.region}</td>{[row[metric][2023],row[metric][2024]].map((amount,index)=><td key={index}>{amount===null?'—':amount.toLocaleString('en-GB',{maximumFractionDigits:2})}</td>)}</tr>)}</tbody></table></div>
 </details>;
}
