'use client';
import {useEffect,useState} from 'react';
import {listCampusFeedbackReports,type CampusFeedbackRecord} from '@/lib/campus-weekly';
import {campusWeeklySections} from '@/lib/campus-weekly-form';
export default function CampusFeedbackRecords({campusId}:{campusId?:string}){const [revision,setRevision]=useState(0);return <FeedbackContent key={`${campusId??'all'}:${revision}`} campusId={campusId} onRefresh={()=>setRevision(value=>value+1)}/>;}
function FeedbackContent({campusId,onRefresh}:{campusId?:string;onRefresh:()=>void}){
 const [records,setRecords]=useState<CampusFeedbackRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;listCampusFeedbackReports(campusId).then(rows=>{if(alive)setRecords(rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[campusId]);
 return <section className="panel padded"><h2>Submitted campus feedback</h2><button className="button" type="button" onClick={onRefresh}>Refresh feedback</button><p className="muted">Latest 100 reports available to your account.</p>{loading&&<p role="status">Loading feedback…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!records.length&&<p>No campus feedback submitted yet.</p>}{records.map(record=><details key={record.id} style={{borderTop:'1px solid var(--border)',padding:'16px 0'}}><summary>{record.campus_name} · Week ending {record.week_ending} · {record.is_late?'Late':'On time'}</summary><p>Submitted by {record.submitter_name} on {new Date(record.created_at).toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>{campusWeeklySections.map(section=><div key={section.title}><h3>{section.title}</h3><dl>{section.fields.filter(([key])=>key!=='tonguesRecipients'||record.answers.holyGhostBaptism==='yes').filter(([key])=>key!=='evangelismZeroReason'||record.answers.evangelismMinutes===0).map(([key,label])=><div key={key}><dt>{label}</dt><dd style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{String(record.answers[key]??'Not provided')}</dd></div>)}</dl></div>)}{record.is_late&&<p>Late reason: {record.answers.lateReason}</p>}</details>)}</section>;
}
