'use client';
import './weekly-forms.css';
import {useState} from 'react';
import type {Campus,Profile} from '@/lib/koc';
import {buildWeeks,deadlineFor,formatDate,type Season} from '@/lib/reporting';
import {campusWeeklySchema,campusWeeklySections,sanitizeCampusWeekly,type CampusWeeklyAnswers} from '@/lib/campus-weekly-form';
import {submitCampusWeeklyFeedback} from '@/lib/campus-weekly';
type Props={season:Season;profile:Profile;campuses:Campus[];campusId?:string;setCampusId?:(id:string)=>void;initialWeek?:string};
export default function CampusWeeklyForm({season,profile,campuses,initialWeek}:Props){
 const campus=campuses.find(item=>item.id===profile.campus_id);const weeks=buildWeeks(season,[]).filter(week=>week.status!=='upcoming');
 const [week,setWeek]=useState(initialWeek??weeks.at(-1)?.weekEnding??'');
 const [draft,setDraft]=useState<Record<string,string>>({evangelismZeroReason:'',incidentNotes:'',lateReason:''});const [answers,setAnswers]=useState<CampusWeeklyAnswers|null>(null);const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [requestId,setRequestId]=useState<string|null>(null);
 const late=Boolean(week&&new Date()>=deadlineFor(week,season));
 function change(key:string,value:string){setDraft(previous=>({...previous,[key]:value}));setSaved(false);setRequestId(null);}
 function review(event:React.FormEvent){event.preventDefault();setError('');const input={...draft};if(input.holyGhostBaptism==='no')delete input.tonguesRecipients;const result=campusWeeklySchema.safeParse(input);const issues:Record<string,string>={};if(!result.success){for(const issue of result.error.issues)issues[String(issue.path[0])]=issue.message;}if(late&&!draft.lateReason?.trim())issues.lateReason='Explain why this submission is late.';if(!week)issues.week='Choose a reporting week.';setErrors(issues);if(result.success&&!Object.keys(issues).length){setAnswers(sanitizeCampusWeekly(result.data));setRequestId(previous=>previous??crypto.randomUUID());}}
 async function submit(){if(!answers||!requestId||busy)return;setBusy(true);setError('');try{await submitCampusWeeklyFeedback(week,answers,requestId);setSaved(true);setAnswers(null);}catch(reason){setError(reason instanceof Error?reason.message:'Submission failed. Please retry.');}finally{setBusy(false);}}
 if(profile.role!=='campus'||profile.status!=='active')return <div className="panel">An approved campus lead account is required.</div>;
 if(!campus||campus.is_active===false)return <div className="panel">Your assigned campus is unavailable for reporting. Contact an administrator.</div>;
 return <section className="campus-weekly-form"><div className="page-heading"><div><h1>Campus weekly feedback</h1><p>Report fellowship, prayer, evangelism and church activity for your campus.</p></div></div>
 {saved&&<div role="status" className="panel">Your campus weekly feedback was submitted successfully.</div>}
 {error&&<div role="alert" className="panel">{error}</div>}
 {answers?<div className="panel"><h2>Review your feedback</h2><p>{profile.full_name} · {campus.name} · Week ending {formatDate(week)}</p><p>Submission status is determined when the platform receives the report.</p>{campusWeeklySections.map(section=><div key={section.title}><h3>{section.title}</h3><dl>{section.fields.filter(([key])=>key!=='tonguesRecipients'||answers.holyGhostBaptism==='yes').filter(([key])=>key!=='evangelismZeroReason'||answers.evangelismMinutes===0).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(answers[key]??'None')}</dd></div>)}</dl></div>)}{answers.lateReason&&<p>Late reason: {answers.lateReason}</p>}<div className="button-row"><button type="button" className="button" disabled={busy} onClick={()=>setAnswers(null)}>Edit answers</button><button type="button" className="button button-yellow" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit feedback'}</button></div></div>:
 <form onSubmit={review} noValidate><div className="panel"><h2>Reporting identity</h2><label>Full name<input className="input" value={profile.full_name} readOnly/></label><label>University / campus<input className="input" value={campus.name} readOnly/></label><label htmlFor="campus-feedback-week">Week ending</label><select className="input" id="campus-feedback-week" value={week} onChange={event=>{setWeek(event.target.value);setRequestId(null);setSaved(false);}}>{weeks.map(item=><option key={item.weekEnding} value={item.weekEnding}>{formatDate(item.weekEnding)}</option>)}</select>{errors.week&&<p role="alert">{errors.week}</p>}<p>{late?'Late — a reason is required.':'Due Friday at 10pm UK time.'} Final late status is determined by the platform.</p></div>
 {campusWeeklySections.map(section=><fieldset className="panel" key={section.title}><legend>{section.title}</legend><div className="form-grid">{section.fields.filter(([key])=>key!=='tonguesRecipients'||draft.holyGhostBaptism==='yes').filter(([key])=>key!=='evangelismZeroReason'||draft.evangelismMinutes==='0').map(([key,label,type])=><div className="field" key={key}><label htmlFor={`feedback-${key}`}>{label}</label>{type==='yesno'?<select className="input" id={`feedback-${key}`} value={draft[key]??''} onChange={event=>change(key,event.target.value)}><option value="">Choose yes or no</option><option value="yes">Yes</option><option value="no">No</option></select>:type==='textarea'?<textarea className="input" id={`feedback-${key}`} rows={3} maxLength={key==='evangelismZeroReason'?1000:4000} value={draft[key]??''} onChange={event=>change(key,event.target.value)}/>:<input className="input" id={`feedback-${key}`} type={type} min={type==='number'?0:undefined} step={type==='number'?1:undefined} value={draft[key]??''} onChange={event=>change(key,event.target.value)}/>} {errors[key]&&<p role="alert">{errors[key]}</p>}</div>)}</div></fieldset>)}
 <div className="panel"><label htmlFor="feedback-lateReason">Reason for late submission {late?'(required)':'(if applicable)'}</label><textarea className="input" id="feedback-lateReason" rows={3} maxLength={1000} value={draft.lateReason??''} onChange={event=>change('lateReason',event.target.value)}/>{errors.lateReason&&<p role="alert">{errors.lateReason}</p>}<button type="submit" className="button button-yellow">Review feedback</button></div></form>}
 </section>;
}
