'use client';
/* eslint-disable @next/next/no-img-element -- Private signed photos must bypass image proxy caches. */
import {useEffect,useState} from 'react';
import {listLeadApplications,applicationPhotoUrl,reviewLeadRequest,type LeadApplication} from '@/lib/lead-applications';
const fields=[['course','Course'],['studyYear','Study year'],['motivation','Why would you like to lead?'],['experience','Fellowship and leadership experience'],['availability','Availability'],['plan','Fellowship plan'],['phone','Phone (optional)'],['email','Email (optional)']] as const;
type Props={campusId?:string;campuses?:{id:string;name:string}[];statuses?:Record<string,string>};
export default function LeadApplicationRecords(props:Props){const [revision,setRevision]=useState(0);return <ApplicationContent key={`${props.campusId??'all'}:${revision}`} {...props} onRefresh={()=>setRevision(value=>value+1)}/>;}
function PrivatePhoto({path}:{path:string}){const [url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let alive=true;applicationPhotoUrl(path).then(value=>{if(alive)setUrl(value);}).catch(()=>{if(alive)setError('Unable to load this private photo.');});return()=>{alive=false;};},[path]);return error?<p role="alert">{error}</p>:url?<img src={url} alt="Applicant face photo" style={{width:180,height:220,objectFit:'contain'}} referrerPolicy="no-referrer"/>:<p role="status">Loading private photo…</p>;}
function RequestRecord({record,campusName,onRefresh}:{record:LeadApplication;campusName:string;onRefresh:()=>void}){const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function decide(status:'approved'|'rejected'){if(busy)return;setBusy(true);setError('');try{await reviewLeadRequest(record.id,status,reason);onRefresh();}catch{setError('The review decision could not be saved.');setBusy(false);}}return <details onToggle={event=>setOpen(event.currentTarget.open)} style={{borderTop:'1px solid var(--border)',padding:'16px 0'}}><summary>{record.answers.fullName} · {record.status??'Legacy application'}</summary><p>{campusName} · {record.kind==='new'?'Start a new KOC':'Lead an existing KOC'}</p><p className="muted small">Requested {new Date(record.created_at).toLocaleString('en-GB',{timeZone:'Europe/London'})} · Reference {record.id}</p>{record.kind==='new'&&<p>{record.answers.newUniversityCity}</p>}{record.photo_path?(open&&<PrivatePhoto key={record.photo_path} path={record.photo_path}/>):<p className="muted small">This earlier application has no face photo.</p>}<dl>{fields.map(([key,label])=><div key={key}><dt>{label}</dt><dd style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',marginBottom:14}}>{String(record.answers[key]||'Not provided')}</dd></div>)}</dl>{record.review_reason&&<p>Review note: {record.review_reason}</p>}{record.status==='pending'&&<div><p>A decision records the request outcome. It does not create an account or grant platform access.</p><label>Review note (optional)<textarea className="input" value={reason} maxLength={2000} onChange={event=>setReason(event.target.value)}/></label><div className="button-row"><button type="button" className="button" disabled={busy} onClick={()=>void decide('approved')}>Approve request</button><button type="button" className="button" disabled={busy} onClick={()=>void decide('rejected')}>Reject request</button></div>{error&&<p role="alert">{error}</p>}</div>}</details>;}
function ApplicationContent({campusId,campuses=[],onRefresh}:Props&{onRefresh:()=>void}){const [records,setRecords]=useState<LeadApplication[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let alive=true;listLeadApplications(campusId).then(rows=>{if(alive)setRecords(rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[campusId]);return <section aria-label="Lead application answers" className="campus-roster-trainees"><h3>Campus leadership requests</h3><p className="muted small">Review applicant details and private photos. Account access is managed separately.</p><button type="button" className="button" onClick={onRefresh}>Refresh requests</button>{loading&&<p role="status">Loading requests…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!records.length&&<p className="muted">No leadership requests yet.</p>}{records.map(record=><RequestRecord key={record.id} record={record} campusName={campuses.find(c=>c.id===record.campus_id)?.name??record.answers.newUniversityName??'Selected university'} onRefresh={onRefresh}/>)}</section>;}
