'use client';
import {useEffect,useState} from 'react';
import {listLeadApplications,type LeadApplication} from '@/lib/lead-applications';
const fields=[['course','Course'],['studyYear','Study year'],['motivation','Why would you like to lead?'],['experience','Fellowship and leadership experience'],['availability','Availability'],['plan','Fellowship plan'],['phone','Phone (optional)']] as const;
type Props={campusId?:string;campuses?:{id:string;name:string}[];statuses?:Record<string,string>};
export default function LeadApplicationRecords(props:Props){const [revision,setRevision]=useState(0);return <ApplicationContent key={`${props.campusId??'all'}:${revision}`} {...props} onRefresh={()=>setRevision(value=>value+1)}/>;}
function ApplicationContent({campusId,campuses=[],statuses={},onRefresh}:Props&{onRefresh:()=>void}){
 const [records,setRecords]=useState<LeadApplication[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;listLeadApplications(campusId).then(rows=>{if(alive)setRecords(rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[campusId]);
 return <section aria-label="Lead application answers" className="campus-roster-trainees"><h3>Lead application answers</h3><p className="muted small">Review these details before approving access in Accounts &amp; access.</p><button type="button" className="button" onClick={onRefresh}>Refresh applications</button>{loading&&<p role="status">Loading applications…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!records.length&&<p className="muted">No lead applications yet.</p>}{records.map(record=><details key={record.id} style={{borderTop:'1px solid var(--border)',padding:'16px 0'}}><summary>{record.answers.fullName} · @{record.answers.username}{statuses[record.user_id]?` · ${statuses[record.user_id]}`:''}</summary><p>{campuses.find(c=>c.id===record.campus_id)?.name??record.answers.newUniversityName??'Selected university'} · {record.kind==='new'?'Start a new KOC':'Lead an existing KOC'}</p><p className="muted small">Applied {new Date(record.created_at).toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>{record.kind==='new'&&<p>{record.answers.newUniversityCity}</p>}<dl>{fields.map(([key,label])=><div key={key}><dt>{label}</dt><dd style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',marginBottom:14}}>{String(record.answers[key]||'Not provided')}</dd></div>)}</dl></details>)}</section>;
}
