'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useForm,useWatch,type Resolver,type FieldError} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {ArrowRight,Check,ArrowLeft} from 'lucide-react';
import BrandLogo from '@/components/ui/brand-logo';
import {ThemeToggle} from '../theme';
import {leadApplicationSchema,type LeadApplicationInput} from '@/lib/lead-application-schema';
import {listApplicationCampuses,submitLeadApplication,type ApplicationCampus} from '@/lib/lead-applications';
import './lead-application-form.css';

const statusLabel=(value:ApplicationCampus['lifecycle_status'])=>value==='in_process'?'In process':value==='inactive'?'Inactive':'Active';
function ErrorNote({error}:{error?:FieldError}){return error?<small className="application-error">{error.message}</small>:null;}
export default function LeadApplicationForm(){
 const [campuses,setCampuses]=useState<ApplicationCampus[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[error,setError]=useState(''),[stage,setStage]=useState<'edit'|'review'|'success'>('edit'),[review,setReview]=useState<LeadApplicationInput|null>(null),[busy,setBusy]=useState(false);
 const stepHeading=useRef<HTMLHeadingElement|null>(null);
 const retry=useRef<{id:string;fingerprint:string}>({id:'',fingerprint:''});
 const {register,handleSubmit,control,setValue,reset,formState:{errors}}=useForm<LeadApplicationInput>({resolver:zodResolver(leadApplicationSchema) as Resolver<LeadApplicationInput>,defaultValues:{kind:'existing',campusId:null,fullName:'',username:'',password:'',newUniversityName:'',newUniversityCity:'',course:'',studyYear:1,motivation:'',experience:'',availability:'',plan:'',phone:'',requestId:''}});
 const kind=useWatch({control,name:'kind'});
 useEffect(()=>{retry.current.id=crypto.randomUUID();setValue('requestId',retry.current.id);let alive=true;listApplicationCampuses().then(rows=>{if(alive)setCampuses(rows);}).catch(()=>{if(alive)setLoadError('Unable to load universities. Refresh this page and try again.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[setValue]);
 function prepare(values:LeadApplicationInput){const fingerprint=JSON.stringify({...values,requestId:undefined});if(retry.current.fingerprint&&retry.current.fingerprint!==fingerprint)retry.current.id=crypto.randomUUID();retry.current.fingerprint=fingerprint;setValue('requestId',retry.current.id);setReview({...values,requestId:retry.current.id});setError('');setStage('review');}
 async function submit(){if(!review||busy)return;setBusy(true);setError('');try{await submitLeadApplication(review);setReview(null);reset();retry.current.fingerprint='';setStage('success');}catch{setError('Your application could not be submitted. Check your details and try again.');}finally{setBusy(false);}}
 useEffect(()=>{if(stage==='review'||stage==='success'){stepHeading.current?.focus();stepHeading.current?.scrollIntoView?.({block:'start'});}},[stage]);
 const university=review?.kind==='new'?`${review.newUniversityName}, ${review.newUniversityCity}`:campuses.find(campus=>campus.id===review?.campusId)?.name??'Selected university';
 return <main className="lead-application">
  <header className="application-header"><Link href="/" className="application-brand"><BrandLogo/><span>Kharis On Campus</span></Link><div><ThemeToggle/><Link href="/login">Already registered? Sign in <ArrowRight size={15}/></Link></div></header>
  <div className="application-layout"><aside className="application-intro"><p className="application-eyebrow">CAMPUS LEADERSHIP</p><h1>Help your campus<br/>grow in faith.</h1><p>Apply to lead an existing KOC or start a fellowship at your university. Tell the team about yourself and how you would support your campus community.</p><ol className="application-progress"><li className={stage==='edit'?'current':''}><span>01</span>Your application</li><li className={stage==='review'?'current':''}><span>02</span>Review and submit</li><li className={stage==='success'?'current':''}><span>03</span>Leadership review</li></ol><p className="application-intro-note">Your account uses a username and password. Email is optional and can be added to your profile later. Campus access starts after approval.</p></aside>
  <section className="application-content" aria-live="polite">
   {stage==='success'?<div className="application-success"><Check size={26}/><p className="application-eyebrow">SUBMITTED</p><h2 ref={stepHeading} tabIndex={-1}>Application received</h2><p>The KOC leadership team will review your application. Sign in with your username and password to check your account&apos;s approval status.</p><Link href="/login" className="application-primary">Continue to sign in <ArrowRight size={17}/></Link></div>:stage==='review'&&review?<>
    <p className="application-eyebrow">CHECK YOUR DETAILS</p><h2 ref={stepHeading} tabIndex={-1}>Review your application</h2><p className="application-description">Check your answers before sending them to the KOC leadership team.</p>
    <dl className="application-review"><dt>Full name</dt><dd>{review.fullName}</dd><dt>Username</dt><dd>{review.username}</dd><dt>Application</dt><dd>{review.kind==='new'?'Start a new KOC':'Lead an existing KOC'}</dd><dt>University</dt><dd>{university}</dd><dt>Course</dt><dd>{review.course}</dd><dt>Study year</dt><dd>Year {review.studyYear}</dd><dt>Phone</dt><dd>{review.phone||'Not provided'}</dd><dt>Password</dt><dd>Set for your account · hidden</dd></dl>
    {([['Why you would like to lead',review.motivation],['Experience',review.experience],['Availability',review.availability],['Campus plan',review.plan]] as const).map(([label,value])=><div className="application-review-answer" key={label}><h3>{label}</h3><p>{value}</p></div>)}
    {error&&<p className="application-error" role="alert">{error}</p>}<div className="application-review-actions"><button type="button" onClick={()=>{setStage('edit');setError('');}} disabled={busy} className="application-secondary"><ArrowLeft size={16}/>Edit application</button><button type="button" onClick={submit} disabled={busy} className="application-primary">{busy?'Submitting…':'Submit application'}<ArrowRight size={17}/></button></div>
   </>:<><p className="application-eyebrow">BECOME A CAMPUS LEAD</p><h2>Your application</h2><p className="application-description">All fields are required unless marked optional. You will review your answers before submitting.</p>
    {loadError&&<p className="application-error" role="alert">{loadError}</p>}
    <form className="application-form" onSubmit={event=>{void handleSubmit(prepare)(event);}} noValidate>
     <fieldset><legend><span>01</span>About you</legend><div className="application-field-row"><label>Full name<input autoComplete="name" maxLength={100} {...register('fullName')}/><ErrorNote error={errors.fullName}/></label><label>Phone number (optional)<input type="tel" autoComplete="tel" maxLength={40} {...register('phone')}/><small>Include your country code.</small><ErrorNote error={errors.phone}/></label></div><div className="application-field-row"><label>Course<input maxLength={120} {...register('course')}/><ErrorNote error={errors.course}/></label><label>Year of study<select {...register('studyYear',{valueAsNumber:true})}>{Array.from({length:10},(_,index)=><option key={index+1} value={index+1}>Year {index+1}</option>)}</select><ErrorNote error={errors.studyYear}/></label></div></fieldset>
     <fieldset><legend><span>02</span>Your university</legend><div className="application-kind"><label><input type="radio" value="existing" {...register('kind')}/>Lead an existing KOC</label><label><input type="radio" value="new" {...register('kind')}/>Start a KOC at a new university</label></div>{kind==='existing'?<label>University<select aria-label="University" {...register('campusId')} defaultValue="" disabled={loading||!!loadError}><option value="">{loading?'Loading universities…':'Select your university'}</option>{campuses.map(campus=><option key={campus.id} value={campus.id}>{campus.name} · {statusLabel(campus.lifecycle_status)}</option>)}</select><small>Inactive and in-process campuses can receive leadership applications.</small><ErrorNote error={errors.campusId}/></label>:<div className="application-field-row"><label>University name<input maxLength={160} {...register('newUniversityName')}/><ErrorNote error={errors.newUniversityName}/></label><label>University city<input maxLength={100} {...register('newUniversityCity')}/><ErrorNote error={errors.newUniversityCity}/></label></div>}</fieldset>
     <fieldset><legend><span>03</span>Your fellowship and leadership</legend><label>Why would you like to lead a KOC?<textarea rows={4} maxLength={3000} {...register('motivation')}/><small>At least 20 characters. Share what motivates you.</small><ErrorNote error={errors.motivation}/></label><label>Your leadership or fellowship experience<textarea rows={4} maxLength={3000} {...register('experience')}/><small>At least 20 characters. If you are new to leadership, tell us that and how you hope to learn.</small><ErrorNote error={errors.experience}/></label><label>Your availability<textarea rows={3} maxLength={1000} {...register('availability')}/><small>Tell us when you can support your campus fellowship.</small><ErrorNote error={errors.availability}/></label><label>Your plan for the campus<textarea rows={4} maxLength={3000} {...register('plan')}/><small>At least 20 characters. Describe how you would gather students and build fellowship.</small><ErrorNote error={errors.plan}/></label></fieldset>
     <fieldset><legend><span>04</span>Create your account</legend><div className="application-field-row"><label>Username<input autoComplete="username" autoCapitalize="none" spellCheck={false} maxLength={30} {...register('username')}/><small>3–30 letters, numbers or underscores.</small><ErrorNote error={errors.username}/></label><label>Password<input type="password" autoComplete="new-password" maxLength={128} {...register('password')}/><small>At least 12 characters.</small><ErrorNote error={errors.password}/></label></div><p className="application-form-note">Keep your username and password. Your account will remain pending until an administrator reviews your application.</p></fieldset>
     <button className="application-primary" type="submit" disabled={kind==='existing'&&(loading||!!loadError)}>Review application <ArrowRight size={17}/></button>
    </form>
   </>}
  </section></div><footer className="application-footer">Kharis On Campus · Campus leadership applications</footer>
 </main>;
}
